###### DCS Lab UOP 2024 ###############################
###### Author Manolis Bozis ########################### 
###### general parameters section #####################


############################### Folders Configuration (set only SCRIPTS_FN variable #################################################
export SCRIPTS_FN="scripts"                                                                                                         #
export USERFOLDER="/home/${USER}"                                                                                                   #
export USER_SCRIPTS_FOLDER="${USERFOLDER}/${SCRIPTS_FN}"                                                                            #
export CONFIGURATION_FOLDER="${USERFOLDER}/${SCRIPTS_FN}/configuration"                                                             #
export LOGS_FOLDER="${USERFOLDER}/${SCRIPTS_FN}/logs"                                                                               #
export CAPTURE_DIRECTORY="${USERFOLDER}/${SCRIPTS_FN}/captures"                                                                     #
export GNB_EXEC_FOLDER=${USERFOLDER}"/openairinterface5g/cmake_targets/ran_build/build/" # Folder where nr-softmodem executable is  #
export CI_SCRIPTS_FOLDER=${USERFOLDER}"/openairinterface5g/ci-scripts/" # Folder where ci-scripts are                               #
#####################################################################################################################################

##### Network Interface Controller settings (set them manually in this file) ##################################
export ROUTER_IP="195.251.38.129"  # change this value to your router IP address                              # 
export NICNAME_0="enp2s0f1"        # NIC connected to UE Host                                                 #
export NICNAME_1="enp1s0f0np0"     # NIC 1 to SDR                                                             #
export NICNAME_2="enp1s0f1np1"     # NIC 2 to SDR                                                             #
export UE_HOST_MAC="cc:96:e5:35:2a:ea"                                                                        #
export GNB_HOST_MAC="84:69:93:80:08:d3"                                                                       #
export LAN_B_ADDR="195.251.38.159"                                                                            #
export GNB_USRP_SERIAL=3177E4C        # replace with your device's serial number                              #
###############################################################################################################

############################### Network Configuration (do mot edit those values) ##############################
  
export UPF_IP="192.168.70.134"; # controlled by gnbconfig -a
export OAI_EXT_DN_IP="192.168.70.135"; # controlled by gnbconfig -a
export AMF_IP="192.168.70.132"; # controlled by gnbconfig -a
export UE_HOST_IP="195.251.38.145"; # controlled by gnbconfig -a
export GNB_HOST_IP="195.251.38.158"; # controlled by gnbconfig -a
export GNB_USRP_MGMT_IP="192.168.20.2"  # controlled by gnbconfig -a
###############################################################################################################

############################### Core Netwrok Host Configuration #########################################     
####### If core network is installed in the same host with gNB leave the following variable blank #######     
                            # run ./netsetupcn in gNB host to create the route                          #     
                            # before running the ./startgnb or ./startgnbsim                            #     
export CN_IP=${GNB_HOST_IP}     # <--put the CN host ip here                                            #    
export GNB_NIC_TO_CN="enp2s0f1" #<--put the NIC name of your interface connecting gNB and CN            #     
export GNB_NIC_TO_CN_IP="192.168.0.1" #<--put the NIC IP of your interface connecting gNB and CN        #     
export CN_HOST_IP="192.168.0.2" #<--put the IP address of the CN host interface connected to gNB host   #     
export GNB_NIC_TO_CN_CDR="${GNB_NIC_TO_CN_IP}/24"                                                       #         
#########################################################################################################     



#################################### Connectivity scenarios ###################################################
# the following variables need to be updated only when new scenarios are added
export SCENARIOS=( "sa_band78_24prb" "sa_band78_51prb" "sa_band78_106prb" "sa_band78_133prb" "sa_band78_162prb" "sa_band78_217prb" \
 "sa_band77_273prb" "sa_band78_106prb_TDD_1" "sa_band78_106prb_TDD_2" "sa_mimo_band78_106prb" \
 "sa_mimo_band78_133prb" "sa_mimo_band78_162prb" "sa_mimo_band78_217prb"  \
 "sa_mimo_band77_273prb" "sa_band66_106prb" "sa_band71_106prb" "dora" "phytest" "phytestextended" \
  "band66_25prb" "geo_sat_emulation" "sa_band3_52prb" )

export CONFIGURATIONS=( "gnb.sa.band78.fr1.24PRB.usrpn310.conf" "gnb.sa.band78.fr1.51PRB.usrpn310.conf" "gnb.sa.band78.fr1.106PRB.usrpn310.conf" \
 "gnb.sa.band78.fr1.133PRB.usrpn310.conf" \
 "gnb.sa.band78.fr1.162PRB.usrpn310.conf" "gnb.sa.band78.fr1.217PRB.usrpn310.conf" "gnb.sa.band77.fr1.273PRB.usrpn310.conf" \
 "gnb.sa.band78.fr1.106PRB.usrpn310_TDD_1.conf" "gnb.sa.band78.fr1.106PRB.usrpn310_TDD_2.conf" "gnb.sa.band78.fr1.106PRB.2x2.usrpn310.conf" \
 "gnb.sa.band78.fr1.133PRB.2x2.usrpn310.conf" "gnb.sa.band78.fr1.162PRB.2x2.usrpn310.conf" "gnb.sa.band78.fr1.217PRB.2x2.usrpn310.conf" \
 "gnb.sa.band77.fr1.273PRB.2x2.usrpn310.conf" "gnb.sa.band66.fr1.106PRB.usrpn310.conf" "gnb.sa.band71.fr1.106PRB.usrpn310.conf" \
 "gnb.sa.band78.tm1.106PRB.usrpn300.conf" "gnb.sa.band78.tm1.106PRB.usrpn300.conf" "gnb.sa.band78.tm1.106PRB.usrpn300.conf" \
 "gnb.sa.band66.fr1.25PRB.usrpn310.conf" "gnb.sa.band66.fr1.25PRB.rfsim.geo.conf" "gnb.sa.band3.fr1.52PRB.usrpn310.conf" )
export MODE_FOR_PANEL="./startgnb"
export OTA_SCENARIOS=21 
export VERSIONS=( "v_1_5" "v_2_1_0" ) 
function print_scenarios() {
cat << EOF 
                           ------------------------------------------------------------------
                          | 1 | standalone mode band 78 with 24prb  (SISO)                   |                            
                          | 2 | standalone mode band 78 with 51prb  (SISO)                   |                          
                          | 3 | standalone mode band 78 with 106prb (SISO)                   |
                          | 4 | standalone mode band 78 with 133prb (SISO)                   |                      
                          | 5 | standalone mode band 78 with 162prb (SISO)                   |      
                          | 6 | standalone mode band 78 with 217prb (SISO)                   |  
                          | 7 | standalone mode band 77 with 273prb (SISO)                   |   
                          | 8 | standalone mode band 78 with 106prb TDD 1 slot configuration |
                          |   | with 7 DL, 2 UL, 1 FL slots, Periodicity=10 Slots            |
                          | 9 | standalone mode band 78 with 106prb TDD 2 slot configuration |
                          |   | with 2 DL, 1 UL, 1 FL slots, Periodicity=4 Slots             |                     
                          | 10| standalone mode band 78 with 106prb (2x2 MIMO)               |
                          | 11| standalone mode band 78 with 133prb (2x2 MIMO)               |
                          | 12| standalone mode band 78 with 162prb (2x2 MIMO)               |     
                          | 13| standalone mode band 78 with 217prb (2x2 MIMO)               |  
                          | 14| standalone mode band 77 with 273prb (2x2 MIMO)               |
                          | 15| standalone mode band 66 with 106prb (SISO,FDD, 40MHz BWP)    |
                          | 16| standalone mode band 71 with 106prb (SISO,FDD, 20MHz BWP)    |                        
                          | 17| do-ra mode: simulated 5G NSA connection with only 5G         |
                          |   | terminals being present                                      |                                              
                          | 18| physical layer test with one slot assigned for downlink      |
                          | 19| extended phy layer test with parameters changed              |
                          |   | (parameters need to be changed directly to script code)      |  
                          | 20| standalone mode band 66 with 25 prb (SISO,FDD, 5MHz BWP)     | 
                          | 21| GEO trnasparent SAT emulation                                |
                          |   | (band 66 with 25 prb (SISO,FDD, 15KHz SCS)                   |  
                          | 22| standalone mode band 3 with 52prb (SISO,FDD, 10MHz BWP)      |                                                  
                          -------------------------------------------------------------------                                           
EOF
} 

################################################################################################################
export PLMNS=( "PLMN_1_" "PLMN_2_" "PLMN_3_" )
# PLMNs List ##############
# PLMN1  --> 00101export GNB_HOST_IP_CIDR="${GNB_HOST_IP}/27"  
# PLMN2  --> 50501
# PLMN3  --> 20295
###########################
################################################################################################################

##########COLOR CODES AND OTHER VARs #################################
export R='\033[0;31m'   #'0;31' is Red's ANSI color code
export G='\033[0;32m'   #'0;32' is Green's ANSI color code
export Y='\033[0;33m'   #'0;33' is Yellow's ANSI color code
export NOCOLOR='\033[0m'
###############################################################################################
export EDITORS=( "nano" "gedit" )
export SELECTED_EDITOR=1 # default editor is nano                                                                      
export NRSCOPE="" # do not use nr-scope tool by default                                                         
export LOG=0      # do not write to a log file (default). You can change it with the -l argument                
export TRACER=0   # do not use tracer tool (default)                                                            
export LOG_FILE_TIMESTAMP=$(date +%d_%m_20%y_at_%H_%M_%S)           
export PDU_SESSION_CREATED=1                                            
############################################################################################## 


############################ gNB parameters to resolve realtime issues ##########################################
                                                                                                                #
################ MAX MCS #####################################################################                  #   
export UL_MAX_MCS=28
export DL_MAX_MCS=28    
export FREQUENCY_SOURCE=1
export ONE_PPS_SOURCE=1    export GNB_HOST_IP_CIDR="${GNB_HOST_IP}/27"  
export MIN_RXTXTIME="--gNBs.[0].min_rxtxtime 6"                                                                  #
#export THREAD_POOL="--thread-pool 0-7"    
#export THREAD_POOL=""                  # better performance with no thread pool configured                     #
##############################################################################################                  #
                                                                                                                #
########################### helps to reduce the ra msg3 retransmissions ######################                  #
export OAI_RA_FIX=""                                                                                           #
#export OAI_RA_FIX="-A 45" # use this parameter when OAI nrUE implementation is connected to gNB                #
#export OAI_RA_FIX=""
##############################################################################################                  #
                                                                                                                #
################# reduce the number of LDPC decoder iterations, ##############################                  # 
################# which will make the LDPC decoder take less time ############################                  #
export LDPC_DECODER_ITERATIONS="--L1s.[0].max_ldpc_iterations 10"                                                #
##############################################################################################                  #
                                                                                                                #
########################## CPU AFFINITY ######################################################                  #
# select the cores you want to allocate to nr-softmodm execution                                                #
# export CPU_AFFINITY="taskset --cpu-list 0-7 "                                                                 #
#export CPU_AFFINITY=                         # no CPU affinity                                                 #
##############################################################################################                  #
                                                                                                                #
                                                                                                                #                                                        
#################################################################################################################

########### OPTIMAL COTS UE settings ##################################
#export ATT_TX=10                                                     # 
#export ATT_RX=10                                                     #
#export MAX_RX_GAIN=50                                                #
#     pusch_TargetSNRx10         = 250;                               #
#     pucch_TargetSNRx10         = 250;                               #
# use all CPUs without THREAD_POOL                                    #
#######################################################################


########### OPTIMAL OAI UE settings (RF cables with 30db att) #########
# Maximum Dl thoughtput achieved near 100mbps for 100MHz BWP          #
# because of the nr-uesoftmodem implementation constraints            #
#export ATT_TX=5                                                      # 
#export ATT_RX=0                                                      #
#export MAX_RX_GAIN=45                                                #                                        
#######################################################################