###### DCS Lab UOP 2024 ###############################
###### Author Manolis Bozis ########################### 
###### general parameters section #####################


############################### Folders Configuration #########################################################
export SCRIPTS_FN="scripts"
export USERFOLDER="/home/${USER}"
export USER_SCRIPTS_FOLDER="${USERFOLDER}/${SCRIPTS_FN}"
export CONFIGURATION_FOLDER="${USERFOLDER}/${SCRIPTS_FN}/configuration"
export LOGS_FOLDER="${USERFOLDER}/${SCRIPTS_FN}/logs"
export CAPTURE_DIRECTORY="${USERFOLDER}/${SCRIPTS_FN}/captures"
export GNB_EXEC_FOLDER=${USERFOLDER}"/openairinterface5g/cmake_targets/ran_build/build/" # Folder where nr-softmodem executable is
export CI_SCRIPTS_FOLDER=${USERFOLDER}"/openairinterface5g/ci-scripts/" # Folder where ci-scripts are
###############################################################################################################

############################### Network Configuration #########################################################
export ROUTER_IP="195.251.38.129" # change this value to your router IP address
export EXT_DN_IP="192.168.70.135" # Ip of oai-ext-dn container
export UPF_IP="192.168.70.134" # IP address of oai-upf container
export UE_HOST_IP="195.251.38.145"
export GNB_HOST_IP_CIDR="195.251.38.158/27"
###############################################################################################################

############################### Core Netwrok Host Configuration ###############################################
####### If core network is installed in the same host with gNB leave the following variable blank #############
# export CN_IP="195.251.38.145" # set the IP of Core Network Host 
# export GNB_NIC_TO_CN="eno1"       # the NIC in gNB host used to route traffic to core network
                            # run ./netsetupcn in gNB host to create the route 
                            # before running the ./startgnb or ./startgnbsim
export CN_IP=
export GNB_NIC_TO_CN=
###############################################################################################################

##########COLOR CODES #################################
export R='\033[0;31m'   #'0;31' is Red's ANSI color code
export G='\033[0;32m'   #'0;32' is Green's ANSI color code
export NOCOLOR='\033[0m'
#######################################################


##### gnb parameters ##################################################
export UL_MAX_MCS=6   # Maximum mcs value for UL (default value is 9)
export CPU_AFFINITY="taskset --cpu-list 0-7 " # select the cores you want to allocate to nr-softmodm execution
#export CPU_AFFINITY=                         # no CPU affinity  


