###### DCS Lab UOP 2024 ###############################
###### Author Manolis Bozis ########################### 
###### general parameters section #####################


############################### Folders Configuration #########################################################
export SCRIPTS_FN="scripts"
export USERFOLDER="/home/${USER}"
export USER_SCRIPTS_FOLDER="${USERFOLDER}/${SCRIPTS_FN}"
export CONFIGURATION_FOLDER="${USERFOLDER}/${SCRIPTS_FN}/configuration"
export LOGS_FOLDER="${USERFOLDER}/${SCRIPTS_FN}/logs"
export CAPTURE_DIRECTORY="${USERFOLDER}/${SCRIPTS_FN}/captures"
export GNB_EXEC_FOLDER=${USERFOLDER}"/openairinterface5g/cmake_targets/ran_build/build/" # Folder where nr-softmodem executable is
export CI_SCRIPTS_FOLDER=${USERFOLDER}"/openairinterface5g/ci-scripts/" # Folder where ci-scripts are
###############################################################################################################

############################### Network Configuration #########################################################
export ROUTER_IP="195.251.38.129" # change this value to your router IP address
export EXT_DN_IP="192.168.70.135" # Ip of oai-ext-dn container
export UPF_IP="192.168.70.134" # IP address of oai-upf container
export UE_HOST_IP="195.251.38.145"
export GNB_HOST_IP_CIDR="195.251.38.158/27"
###############################################################################################################

############################### Core Netwrok Host Configuration ###############################################
####### If core network is installed in the same host with gNB leave the following variable blank #############
# export CN_IP="195.251.38.145" # set the IP of Core Network Host 
# export GNB_NIC_TO_CN="eno1"       # the NIC in gNB host used to route traffic to core network
                            # run ./netsetupcn in gNB host to create the route 
                            # before running the ./startgnb or ./startgnbsim
export CN_IP=
export GNB_NIC_TO_CN=
###############################################################################################################
#################################### Connectivity scenarios ###################################################
# the followin variable needs to be updated when new scenarios are added
export SCENARIOS=( "sa_band78_51prb" "sa_band78_106prb" "sa_band78_133prb" "sa_band78_162prb" "sa_band78_217prb" \
 "sa_band77_273prb" "sa_band78_106prb_TDD_1" "sa_band78_106prb_TDD_2" "sa_mimo_band78_106prb" \
 "sa_mimo_band78_133prb" "sa_mimo_band78_162prb" "sa_mimo_band78_217prb"  \
 "sa_mimo_band77_273prb" "sa_band66_106prb" "dora" "phytest" "phytestextended" )

export CONFIGURATIONS=( "gnb.sa.band78.51prb.usrpn310.conf" "gnb.band78.sa.fr1.106PRB.usrpn310.conf" "gnb.band78.sa.fr1.133PRB.usrpn310.conf" \
 "gnb.band78.sa.fr1.162PRB.usrpn310.conf" "gnb.sa.band78.fr1.217PRB.usrpn310.conf" "gnb.sa.band77.fr1.273PRB.usrpn310.conf" \
 "gnb.band78.sa.fr1.106PRB.usrpn310_TDD_1.conf" "gnb.band78.sa.fr1.106PRB.usrpn310_TDD_2.conf" "gnb.band78.sa.fr1.106PRB.2x2.usrpn310.conf" \
 "gNB_SA_n78_133PRB.2x2_usrpn310.conf" "gnb.band78.sa.fr1.162PRB.2x2.usrpn310.conf" "gnb.sa.band78.fr1.217PRB.2x2.usrpn310.conf" \
 "gnb.sa.band77.fr1.273PRB.2x2.usrpn310.conf" "gnb.sa.band66.fr1.106PRB.usrpn300.conf" )
 
export OTA_SCENARIOS=14 
 
################################################################################################################
export PLMNS=( "PLMN_1_" "PLMN_2_" "PLMN_3_" )
# PLMNs List ##############
# PLMN1  --> 00101
# PLMN2  --> 50501
# PLMN3  --> 20295
###########################
################################################################################################################

##########COLOR CODES AND OTHER VARs #################################
export R='\033[0;31m'   #'0;31' is Red's ANSI color code
export G='\033[0;32m'   #'0;32' is Green's ANSI color code
export NOCOLOR='\033[0m'
export re='^[0-9]+$'    # integer value for selected scenario to be checked
######################################################################


##### gnb parameters ##################################################
export UL_MAX_MCS=6
export DL_MAX_MCS=16

#export CPU_AFFINITY="taskset --cpu-list 0-7 " # select the cores you want to allocate to nr-softmodm execution
export CPU_AFFINITY=                         # no CPU affinity  
SELECTED_PLMN=1 # default PLMN is 00101

NRSCOPE="" # do not use nr-scope tool by default
LOG=0      # do not write to a log file (default). You can change it with the -l argument
TRACER=0   # do not use tracer tool (default)
LOG_FILE_TIMESTAMP=$(date +%d_%m_20%y_at_%H_%M_%S)
# OAI_RA_FIX="-A 45" # use this parameter when OAI nrUE implementation is connected to gNB
                   # helps to reduce the ra msg3 retransmissions
OAI_RA_FIX=""

