#!/bin/bash
# creates a tmux panel for the control of gNB and Core Network 
# DCS LAB UOP
# Author Manolis Bozis
# Aug 2024
#
source gnbconfig.ini


ARGS_FOR_STARTGNBSIM=$@
SCRIPT_PANEL=$0
echo -e "${G}preparing to start tmux session ..${NOCOLOR}"
echo -e "${G}passing all arguments to startgnbsim script ..${NOCOLOR}"

sleep 2

if ! tmux has-session -t=gNB_Panel >/dev/null; then
  # if it does not exist
  # create a new session (new -s) called 'gNB_Panel' detached (-d flag)
  ###### panel construction ###############################
  tmux new-session -s "gNB_Panel" -d
else
  echo -e "gNB Panel is already created"
  tmux a -t "gNB_Panel"
  exit 1
fi

##### gNB and AMG log Interface #########################
# create panes
tmux split-window -v -l 18
tmux split-window -v 
tmux split-window -v -l 14
tmux split-window -h 

tmux rename-window -t 0 "gNB_&_AMF_log"
tmux send-keys -t 0 "${MODE_FOR_PANEL} ${ARGS_FOR_STARTGNBSIM}" Enter # execute startgnb or startgnbsim script with provided arguments
tmux send-keys -t 1 "watch -t -n 5 -c ./oaitest -c" Enter                # view AMF log tail
tmux send-keys -t 2 "./oaitest --stats MAC" Enter # send command to startgnb
tmux send-keys -t 3 "./oaitest --stats L1" Enter # send command to startgnb
tmux send-keys -t 0 "tmux display-panes -d 2000" Enter
tmux send-keys -t 4 "watch -t -n 20 -c ./gnbconfig -v" Enter       # display configration for selected scenario


tmux select-pane -t 0 -T "gNB" -P # 'fg=black,bg=colour190'  # switch to nr-softmodem panel to enter password for sudo 
tmux select-pane -t 1 -T "Core Network (AMF)"
tmux select-pane -t 2 -T "Statistics of MAC Layer"
tmux select-pane -t 3 -T "Statistics of Physical Layer"
tmux select-pane -t 4 -T "Configuration parameters"


##### display panes numbers #############################
tmux set -g pane-border-status top
tmux set -g pane-border-format "#{pane_index} #{pane_title}"
tmux set-window-option -g window-status-current-style bg=colour190
tmux a -t "gNB_Panel":"gNB_&_AMF_log".0 # attach to gNB Panel tmux session


#check_PDU(){
#while [[ ${PDU_SESSION_CREATED} -ne 0 ]]
#do
#exec ./oaitest -c &
#PDU_SESSION_CREATED=$?
#sleep 10
#done
#}
#./oaitest -c > /dev/null
#GNB_ACTIVE=$?
##### Thoughout and latency tests #######################
#if [[ ${GNB_ACTIVE} -eq 0 ]]; then
#tmux new-window -d -n "Throughput_and_latency_tests" -t "gNB_&_AMF_log"
#tmux split-window -v
#tmux send-keys -t 1 "./oaitest -s" Enter
#fi
# show active sessions ###################
#tmux ls


