#!/bin/bash
# DCS LAB
# UOP
# Manolis Bozis Mar 2023
# Open Air Interface 5g NR SA E2E testbed
# Script to check different scenarios on 5G SA E2E link 
# ---!!! run it without root privilages !!!----
# in order to run tests UE needs to have a PDU session established
# to core network
# NETWORK CONFIGURATION
# add to your /etc/hosts file
# amf 192.168.70.132
# ue 192.168.45.8
# 5gcn IP needs to be set accordingly to host OR VM IP 
# (make changes to /etc/hosts file)
# 5gcn VM or actual host needs to have ssh HOST keys installed
# so that to accept password less ssh connections
# ----------------------------
#---------COLOR CODES --------------------
R='\033[0;31m'   #'0;31' is Red's ANSI color code
G='\033[0;32m'   #'0;32' is Green's ANSI color code
NOCOLOR='\033[0m'
#ROUTER_IP="195.251.38.129"
ROUTER_IP="195.251.38.129" # router ip for DCS LAB

PING_COUNT=40
###############################
######### FUCTIONS ############
#### FUNCTION 1 Exit Script ###
exitScript(){
echo -e "exiting....\n"
sleep 2
exit 1
}
#### FUNCTION 2 Check UE Registration to 5G Network #####
checkUERegistration(){
# check if oai_tun interface is UP
# check first if 5gcn is reachable
ping -c 1 5gcn >/dev/null
CNHOST=$?
if [ $CNHOST -eq 0 ]
  then
   ssh 5gcn "docker logs oai-amf | tail -n 5 | grep 5GMM-REGISTERED"
   REGISTERED=$?
#   clear (removed not to lose screen buffer data)
   if [ $REGISTERED -eq 0 ]
     then
       echo -e "${G} UE has been registered successfully${NOCOLOR}\n"
       UE_REGISTERED_FLAG=1 # fla195.251.38.129g to report successful registration to other functions
     else
       echo -e "${R}UE has not been registered to Core Network${NOCOLOR}\n"
       exitScript
     fi
   else
       echo -e "${R}5G core network host is down or unreachable${NOCOLOR}\n"
       exitScript
fi
# FIND UE IP ASSIGNED ADDRESS
ping -c 1 ue > /dev/null
NRUEHOST=$?
if [ "${NRUEHOST}" -eq '0' ]
   then
   UE_INET=$(ssh ue "ip a  | grep 12.1.1")
   if [ "${UE_INET}" == "" ]
     then 
       echo -e "${R}UE has not been asigned an IP address${NOCOLOR}"
       exitScript
     else
       UE_IP=$(echo ${UE_INET} | tr '/' ' ' | cut -d " " -f 2)
       echo -e "${G}UE has been asigned IP address ${UE_IP}${NOCOLOR}"

     fi
   else
       echo -e "${R}UE host is down or unreachable${NOCOLOR}\n"
       exitScript
fi
# check if core network is up
ping -c 1 amf >/dev/null
CN_UP=$?
if [ $CN_UP -eq 0 ]
then
   echo -e "${G}5G network is up and running${NOCOLOR}\n"
else
   echo -e "${R}5G network is not accesible${NOCOLOR}\n"
   exitScript
fi
}
##########################################################################

#### FUNCTION 3 RTT Tests with ping command ###################
pingtests(){
# do ping connectivity tests from UE side
# ping lab router from UE
echo -e "${G}Starting pinging from UE to lab router${NOCOLOR}\n"
ssh ue "ping ${ROUTER_IP} -c ${PING_COUNT} -I oaitun_ue1"

#  ping test from oai-ext-dn container to UE
echo -e "${G}start pinging from core network to UE${NOCOLOR}\n"
ssh 5gcn "docker exec oai-ext-dn ping $UE_IP -c ${PING_COUNT}"
}
##########################################################################
#### FUNCTION 4 Throughput Test with iperf command in Downlink ###########
iperftestDL(){
# start iperf server deamon on UE side
ssh ue "pgrep iperf >/dev/null"
iperf_RUNNING=$?
if [ ${iperf_RUNNING} -eq 0 ]
then
 echo -e "iperf server is already running\n"
 echo -e "wait a sec to terminate and restart iperf\n"
 ssh ue "pkill iperf"
 sleep 2
fi
 ssh ue "iperf -s -D -u -B $UE_IP"
 iperf_SERVER=$?
  if [ $iperf_SERVER -eq 0 ]
  then
   echo -e "iperf server started succesfully on UE side\n"
  else
   echo -e "iperf server didn't start on UE side\n"
   exitScript
  fi


#
# ssh to 5gcn VM and create traffic from ext-dn container
# 
echo -e "${G}Starting transmitting data on 5G DOWNLINK${NOCOLOR}"
echo -e "${G}Sending DOWNLINK traffic at ${DOWNLINK_SPEED_TEST}bps${NOCOLOR}"
ssh 5gcn "docker exec oai-ext-dn iperf -u -t ${TEST_TIME} -i 1 -fk -B 192.168.70.135 -b ${DOWNLINK_SPEED_TEST} -c $UE_IP"
echo -e "transmission stoped in 5G DOWNLINK"
# -stop iperf server on UE side
ssh ue "pkill iperf"
sleep 2
# 
}
####################################################################
#### FUNCTION 5 Throughput Test with iperf command in Uplink ############
iperftestUL(){
# start iperf server deamon on oai-ext-dn container 
ssh 5gcn "docker exec oai-ext-dn pgrep iperf >/dev/null"
iperf_RUNNING=$?
if [ ${iperf_RUNNING} -eq 0 ]
then
 echo -e "iperf server is already running\n"
 echo -e "wait a sec to terminate and restart iperf\n"
 ssh 5gcn "docker exec oai-ext-dn pkill -KILL iperf"
 sleep 2
fi
 ssh 5gcn "docker exec oai-ext-dn iperf -s -D -u -B 192.168.70.135"
 iperf_SERVER=$?
  if [ $iperf_SERVER -eq 0 ]
  then
   echo -e "iperf server started succesfully on oai-ext-dn container\n"
  else
   echo -e "iperf server didn't start on oai-ext-dn container\n"
   exitScript
  fi

# 
# ssh to UE host and create traffic from UE to oai-ext-dn container
# 
echo -e "${G}Starting transmitting data on 5G UPLINK${NOCOLOR}"
echo -e "${G}Sending UPLINK traffic at ${UPLINK_SPEED_TEST}bps${NOCOLOR}"
ssh ue "iperf -u -t ${TEST_TIME} -i 1 -fk -B ${UE_IP} -b ${UPLINK_SPEED_TEST} -c 192.168.70.135"
echo -e "transmission stoped in 5G UPLINK"
# -stop iperf server on UE side
ssh 5gcn "docker exec oai-ext-dn pkill -KILL iperf"
sleep 2
}
###########################################################################
#### FUNCTION 6 Bandwidth Graph with Speedometer Test on 5G oaitun_ue1 interface  ############
speedometer(){
ssh ue 
export DISPLAY=:1
gnome-terminal -x bash -c "speedometer -t oaitun_ue1 -r aoitun_ue1"
exit # exit from ue session
}
###########################################################################
#### FUNCTION 7 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023
Testing tool for E2E 5G SA system using Open Air Interface with RFsimulator
or 2 hosts running OAI nrUE and nrgNB respectively, connected to SDRs.
SDR link can be OTA or with RF cables
Usage:  $0 [OPTION]... [+VALUE] 
  -c, --check              check UE registration status to 5G Network  
  -u, --uplink [value]     create traffic to uplink. Value needs to be in bps
                           example for 30Mbps: -u 30M   
  -d, --downlink [value]   create traffic to downlink. Value needs to be in bps
                           example for 30Mbps: -d 30M
  -t  --time [value[       time to execute downlink and uplink tests (used with '-d' and '-u' arguments) 
                           [value] is in seconds. If not defined default value is 10
  -r, --rtt                measure rtt executing ping commands in both uplink and
                           downlink
  -h, --help               print this help message
  --dmax                   get downlink throughput
  --umax                   get uplink trhoughput 
EOF
}
######### Function 8 Downlink throughput ###################################
checkDownlinkThroughput(){
# start iperf server deamon on UE side
ssh ue "pgrep iperf >/dev/null"
iperf_RUNNING=$?
if [ ${iperf_RUNNING} -eq 0 ]
then
 echo -e "iperf server is already running\n"
 echo -e "wait a sec to terminate and restart iperf\n"
 ssh ue "pkill iperf"
 sleep 2
fi
 ssh ue "iperf -s -D -B $UE_IP"
 iperf_SERVER=$?
  if [ $iperf_SERVER -eq 0 ]
  then
   echo -e "iperf server started succesfully on UE side\n"
  else
   echo -e "iperf server didn't start on UE side\n"
   exitScript
  fi


#
# ssh to 5gcn VM and create traffic from ext-dn container
# 
echo -e "${G}Starting transmitting data on 5G DOWNLINK${NOCOLOR}"
echo -e "${G}Sending DOWNLINK traffic at ${DOWNLINK_SPEED_TEST}bps${NOCOLOR}"
ssh 5gcn "docker exec oai-ext-dn iperf -B 192.168.70.135 -c $UE_IP"
echo -e "transmission stoped in 5G DOWNLINK"
# -stop iperf server on UE side
ssh ue "pkill iperf"
sleep 2
# 

}
###########################################################################

######### Function 9 Uplink throughput ###################################

checkUplinkThroughput(){
ssh 5gcn "docker exec oai-ext-dn pgrep iperf >/dev/null"
iperf_RUNNING=$?
if [ ${iperf_RUNNING} -eq 0 ]
then
 echo -e "iperf server is already running\n"
 echo -e "wait a sec to terminate and restart iperf\n"
 ssh 5gcn "docker exec oai-ext-dn pkill -KILL iperf"
 sleep 2
fi
 ssh 5gcn "docker exec oai-ext-dn iperf -s -D -B 192.168.70.135"
 iperf_SERVER=$?
  if [ $iperf_SERVER -eq 0 ]
  then
   echo -e "iperf server started succesfully on oai-ext-dn container\n"
  else
   echo -e "iperf server didn't start on oai-ext-dn container\n"
   exitScript
  fi

# 
# ssh to UE host and create traffic from UE to oai-ext-dn container
# 
echo -e "${G}Starting transmitting data on 5G UPLINK${NOCOLOR}"
ssh ue "iperf -B ${UE_IP} -c 192.168.70.135"
echo -e "transmission stoped in 5G UPLINK"
# -stop iperf server on UE side
ssh 5gcn "docker exec oai-ext-dn pkill -KILL iperf"
sleep 2

}
###########################################################################

function main() {
  UE_REGISTERED_FLAG=0 # set the initial value of the flag
  TEST_TIME=10
  DOIPERFTESTUL=0
  DOIPERFTESTDL=0

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi

  until [ -z "$1" ]
  do
    case "$1" in
       -c | --check)
            echo "start checking UE registration to 5G network..."
            checkUERegistration
            shift;;
       --umax)
            if [ ${UE_REGISTERED_FLAG} -ne 1 ]
            then
            checkUERegistration       
            fi
            checkUplinkThroughput
            shift;;
       -u | --uplink)
            UPLINK_SPEED_TEST=$2
            if [ ${UE_REGISTERED_FLAG} -ne 1 ]
            then
            checkUERegistration       
            fi
            DOIPERFTESTUL=1
            shift 2;;
       -r | --rtt)
            if [ ${UE_REGISTERED_FLAG} -ne 1 ]
            then
            checkUERegistration       
            fi
            pingtests
            shift;;
       --dmax)
            if [ ${UE_REGISTERED_FLAG} -ne 1 ]
            then
            checkUERegistration       
            fi
            checkDownlinkThroughput
            shift;;
       -d | --downlink)
            DOWNLINK_SPEED_TEST=$2
            if [ ${UE_REGISTERED_FLAG} -ne 1 ]
            then
            checkUERegistration       
            fi        
            DOIPERFTESTDL=1
            shift 2;;
       -t | --time)
            TEST_TIME=$2
            shift 2;;       
	-h | --help)
            print_help
            exit 0;;
        *) 
            exit
            ;;    
    esac
  done
# run uplink and downlink if selected 
if [ ${DOIPERFTESTDL} == 1 ]
then
iperftestDL
fi
if [ ${DOIPERFTESTUL} == 1 ]
then
iperftestUL
fi
#
  }
  
  main "$@"
  
