#!/bin/bash
# uop dcs lab
# Manolis Bozis 
# Feb 2024

################### VARIABLES SECTION ####################################
# Version list
# 1 --> 1.5
# 2 --> 2.0.1
source gnbconfig.ini

###########################
###########################################################################
#### FUNCTION 1 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2024
tool for configuring RF parameters in Open Air Interface gNB
Usage:  $0 [OPTION]... [+VALUE] 
  -e, --external_source        specify SDR clock and time source as external                                 
  -i, --internal_source        specify SDR clock and time source as internal                              
  -t  --att_tx [value]         specify attenuation value in dB (0 - 30) for transmitter                                
                               example: $0 -t 10   
  -r, --att_rx [value]         specify attenuation value in dB (0 - 30) for receiver
                               example: $0 -r 15   
  -v, --view                   view current configuration parameters                             
  -h, --help                   print this help message
EOF
}



###############################################################
########## view settings in configuration files ###############
##########       for every scenario             ###############
view_config(){
SCENARIO=1
for file in ${CONFIGURATIONS[@]}
do
  echo -e "${G}scenario: ${SCENARIO}${NOCOLOR}"
  grep -E 'att_tx|att_rx|sdr_addrs' ${CONFIGURATION_FOLDER}/${file}
((SCENARIO++))
echo "---------------------------------------------"
done
}
###############################################################


########## set att_tx value in configuration file #############
set_att_tx(){
for file in ${CONFIGURATION_FOLDER}/*
do
sed -i "/att_tx/c\         att_tx         = ${SELECTED_TX_VALUE};" ${file}
done
}
###############################################################
########## set att_rx value in configuration file #############
set_att_rx(){
for file in ${CONFIGURATION_FOLDER}/*
do
sed -i "/att_rx/c\         att_rx         = ${SELECTED_RX_VALUE};" ${file}
done
}
###############################################################

### set internal source for SDR in configuration file #########
set_internal(){
for file in ${CONFIGURATION_FOLDER}/*
do
sed -i 's/source=external/source=internal/g;s/source=gpsdo/source=internal/g' ${file}
done
}
###############################################################
### set external source for SDR in configuration file #########
set_external(){
for file in ${CONFIGURATION_FOLDER}/*
do
sed -i 's/source=internal/source=external/g;s/source=gpsdo/source=external/g' ${file}
done
}
###############################################################

###############################################################
### set external source for SDR in configuration file #########
set_gpsdo(){
for file in ${CONFIGURATION_FOLDER}/*
do
sed -i 's/source=internal/source=gpsdo/g;s/source=external/source=gpsdo/g' ${file}
done
}
###############################################################

function main() {
###############################################################
if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###############################################################
 until [ -z "$1" ]
  do
    case "$1" in
         -t | --att_tx)
            SELECTED_TX_VALUE=$2
            if [[ ! ${SELECTED_TX_VALUE} =~ $re ]] || [[ ${SELECTED_TX_VALUE} -gt 60 ]] || [[ ${SELECTED_TX_VALUE} -lt 0 ]] ; then
               echo -e "${R}selected value is not valid. Choose a value from 0 to 60 \n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            set_att_tx
            ###########################################################
            shift 2;;     
        -r | --att_rx)
            SELECTED_RX_VALUE=$2
            if [[ ! ${SELECTED_RX_VALUE} =~ $re ]] || [[ ${SELECTED_RX_VALUE} -gt 60 ]] || [[ ${SELECTED_RX_VALUE} -lt 0 ]] ; then
               echo -e "${R}selected value is not valid. Choose a value from 0 to 30 \n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            set_att_rx 
            ###########################################################
            shift 2;;                 
       -e | --external_source)
            set_external
            shift;;
       -i | --internal_source)
            set_internal
            shift;;  
       -g | --gpsdo_source)
            set_gpsdo
            shift;;               
       -v | --view)
            view_config
            exit 0;;     
       -h | --help)
            print_help
            exit 0;;
        *) 
            exit
            ;;    
    esac
  done
 # start execution of functions to set appropriate values to configuration files

  }

main "$@"


 
