#!/bin/bash
# oai 5G testbed with USRP N310
# UOP
# DCS LAB Oct 2023
# Manolis Bozis
# scripts MUST run with root privillages
# 
source ueconfig.ini
###############################

#######################  VARIABLES SECTION ###############################
# the followin variable needs to be updated when new scenarios are added
# scenarios 8 and 9 are the same with 5, so the same function is executed,
# given that TDD slot configuration is in the gNB side

###########################################################################

######### FUCTIONS ############
#### FUNCTION 1 Exit Script ###
exitScript(){
echo -e "exiting....\n"
sleep 2
exit 1
}
###############################

###########################################################################
#### FUNCTION 2 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023
Tool to start UE softmodem for a particular scenorio using Open Air Interface with RFsimulator
or 2 hosts running OAI nrUE and nrgNB respectively.
the ethernet link between the 2 hosts  needs to be at least 10Gbps 

Usage:  $0 [OPTION]... [+VALUE] 
  -s, --scenario [value]   start UE softmodem executing scenario number [value]
                           value is from the following table
                           ------------------------------------------------------------------
                          | 1 | standalone mode band 78 with 51prb  (SISO)                   |                          
                          | 2 | standalone mode band 78 with 106prb (SISO)                   |
                          | 3 | standalone mode band 78 with 133prb (SISO)                   |                      
                          | 4 | standalone mode band 78 with 162prb (SISO)                   |      
                          | 5 | standalone mode band 78 with 217prb (SISO)                   |  
                          | 6 | standalone mode band 77 with 273prb (SISO)                   |   
                          | 7 | standalone mode band 78 with 106prb TDD 1 slot configuration |
                          |   | with 7 DL, 2 UL, 1 FL slots, Periodicity=10 Slots            |
                          | 8 | standalone mode band 78 with 106prb TDD 2 slot configuration |
                          |   | with 2 DL, 1 UL, 1 FL slots, Periodicity=4 Slots             |                     
                          | 9 | standalone mode band 78 with 106prb (2x2 MIMO)               |
                          | 10| standalone mode band 78 with 133prb (2x2 MIMO)               |
                          | 11| standalone mode band 78 with 162prb (2x2 MIMO)               |     
                          | 12| standalone mode band 78 with 217prb (2x2 MIMO)               |  
                          | 13| standalone mode band 77 with 273prb (2x2 MIMO)               |
                          | 14| standalone mode band 66 with 106prb (SISO,FDD)               |
                          | 15| do-ra mode: simualated 5G NSA connection with only 5G        |
                          |   | terminals being present                                      |                      
                          | 16| physical layer test with one slot assigned for downlink      |
                          | 17| extended phy layer test with parameters changed              |
                          |   | (parameters need to be changed directly to script code)      |        
                          -------------------------------------------------------------------
  -o, --scope              use nr-scope tool
  -p, --plmn               PLMN selection
                           1 (default) --> 00101
                           2           --> 50501                          
                           2           --> 20295 
  -i, --info               show Open Air Interface version
  -h, --help               print this help message
EOF
}
###################################### FUNCTION 3  ##########################
# copy raw files from gNB host, to UE host execution folder for the RA process
copy_raw_files(){
scp ${GNB_HOST_USER}@${GNB_HOST_1GBPS_NIC_IP}:${GNB_EXEC_FOLDER}/*.raw ${GNB_EXEC_FOLDER}/
if [[ $? -eq 0 ]] ; then
echo -e "${G}raw Files successfully copied to destination folder ${NOCOLOR}"
else
echo -e "${G}raw Files could not be copied to destination folder ${NOCOLOR}"
exitScript
fi  
sleep 2
}
##############################################################################

################## SCENARIO 1 ##############################################
#################### SA mode band 78 51prb  ################################
# 51 PRB - usrp n310 #######################################################
sa_band78_51prb(){
COMMAND="./nr-uesoftmodem \
-r 51 --numerology 1 --band 78 -C 3309960000 --ssb 222 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 2 ##############################################
#########  SA mode band 78 106prb  #########################################
sa_band78_106prb(){
# RFSIMULATOR=127.0.0.1 ./nr-uesoftmodem -O ${USERFOLDER}/scripts/ue.conf -r 106 --numerology 1 --band 78 -C 3619200000 \
# --nokrnmod --rfsim --sa --uicc0.imsi 001010000000001 --uicc0.nssai_sd 1 \
# -d --telnetsrv --rfsimulator.options chanmod --rfsimulator.modelname rfsimu_channel_gnb0 
COMMAND="./nr-uesoftmodem \
-r 106 --numerology 1 --band 78 -C 3619200000 --ssb 516 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
################################################################################
}
############################################################################

################## SCENARIO 3 ##############################################
sa_band78_133prb(){
COMMAND="./nr-uesoftmodem \
-r 133 --numerology 1 --band 78 -C 3325620000 --ssb 144 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 4 ##############################################
sa_band78_162prb(){
COMMAND="./nr-uesoftmodem \
-r 162 --numerology 1 --band 78 -C 3329760000 --ssb 516 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 5 ##############################################
sa_band78_217prb(){
COMMAND="./nr-uesoftmodem \
-r 217 --numerology 1 --band 78 -C 3339300000 --ssb 1152 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 6 ##############################################
sa_band77_273prb(){
COMMAND="./nr-uesoftmodem \
-r 273 --numerology 1 --band 77 -C 3949740000 --ssb 1492 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

#### IMPORTANT !!! #########################################################
#### SCENARIOS 7 and 8 are the same with scenario 2 ########################
############################################################################

################## SCENARIO 9 ##############################################
sa_mimo_band78_106prb(){
COMMAND="./nr-uesoftmodem \
-r 106 --numerology 1 --band 78 -C 3319680000 --ssb 516 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
# --uicc0.nssai_sd 0xFFFFFF
}
############################################################################

################## SCENARIO 10 #############################################
sa_mimo_band78_133prb(){
COMMAND="./nr-uesoftmodem \
-r 133 --numerology 1 --band 78 -C 3325620000 --ssb 144 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
#-d
}

############################################################################
################## SCENARIO 11 #############################################
sa_mimo_band78_162prb(){
COMMAND="./nr-uesoftmodem \
-r 162 --numerology 1 --band 78 -C 3329760000 --ssb 516 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}

############################################################################

################## SCENARIO 12 #############################################
sa_mimo_band78_217prb(){
COMMAND="./nr-uesoftmodem \
-r 217 --numerology 1 --band 78 -C 3339300000 --ssb 1152 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 13 ##############################################
#################### SA mode band 77 273prb  ###############################
sa_mimo_band77_273prb(){
COMMAND="./nr-uesoftmodem \
-r 273 --numerology 1 --band 77 -C 3949740000 --ssb 1492 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--rfsim --sa --rfsimulator.serveraddr 192.168.0.1 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 14 ##############################################
#################### SA mode band 66 #######################################
sa_band66(){
# band 66 
# FDD
# --numerology 1   (that means 30Khz subcarrier spacing)
# -r (Number of Physical Rsource Blocks PRBs)
# CO (Carrier Offset 400MHz)
# Carrier Frequency 2169080000 Hz
# --ssb (SSB subcarrier offset, substitutesthe older -s which is not valid now

# --------------------------- BAND 66 ---------------------------------------------------------------------------------------------
COMMAND="FSIMULATOR=127.0.0.1 LD_LIBRARY_PATH=. ./nr-uesoftmodem -r 106 --numerology 1 --band 66 -C 2169080000 --CO -400000000 --ssb 396 \
-rfsim --sa --telnetsrv -O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 15 ######### ####################################
#################### Physical do-ra mode ###################################
dora(){
copy_raw_files
COMMAND="LD_LIBRARY_PATH=. ./nr-uesoftmodem --rfsim --rfsimulator.serveraddr ${GNB_HOST_10GBPS_NIC_IP} --do-ra"
}
############################################################################

############## SCENARIO 16 ##################################################-
#################### Physical layer test ###################################
phytest(){
# only 1 slot assigned for downlink
copy_raw_files
COMMAND="LD_LIBRARY_PATH=. ./nr-uesoftmodem --rfsim --rfsimulator.serveraddr ${GNB_HOST_10GBPS_NIC_IP} --phy-test" 
}

############################################################################


############## SCENARIO 17 ##################################################-
#################### Physical layer test with parameters  ##################
phytestextended(){
#  new parameters added on gNB side scripts (startuesim)
# -m     MCS (Modulation Coding Scheme)
# -M     number of resource blocks asigned
# -D     Bitmap of slots in downlink
# Selections are MCS=27 PRBs=106  
# and Bitmap of slots = 126 decimal = 01111110 binary that coresponds to slots 1,2,3,4,5 and 6
# at the UE side we see the number of HACKs are 6 times greater than in 1st scenario
copy_raw_files
COMMAND="LD_LIBRARY_PATH=. ./nr-uesoftmodem --rfsim --rfsimulator.serveraddr ${GNB_HOST_10GBPS_NIC_IP} --phy-test"
}
############################################################################




######################## MAIN FUNCTION #####################################
function main() {

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###########################################################

# check arguments

  until [ -z "$1" ]
  do
    case "$1" in
       -i | --info)
            echo "getting the version of OAI software..."
            sleep 1
            cd ${USERFOLDER}/openairinterface5g/
            echo -e "The version of the Open Air Interface is: $(git show | grep 'Merge branch' | cut -d "'" -f 2)\n"
            exit 0
            shift;;
       -s | --scenario)
            # check if scenario value is valid
            SELECTED_SCENARIO=$2
            if [[ ! $SELECTED_SCENARIO =~ $re ]] || [[ $SELECTED_SCENARIO -gt ${#SCENARIOS[@]} ]] || [[ $SELECTED_SCENARIO -le 0 ]] ; then
               echo -e "${R}selected senario is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################

            # check if core network is up, executing a ping to AMF ####
            #echo -e "checking connection to AMF...\n"
            #ping amf -c 1
            #if [ $? -ne 0 ]; then
            #echo -e "${R} No connection to AMF\n"
            #echo -e "start 5G core network prior to executing RAN\n"
            #echo -e "or check your network settings ${NOCOLOR}\n"
            #exit 1
            #fi 
            ###########################################################

            # check cpu state #########################################
            cpufreq-info | awk '/analyzing CPU/ || /current CPU frequency is/ {print}'
            ###########################################################
            # switch to softmodem binary file folder ##################
            cd ${USERFOLDER}/openairinterface5g
            source oaienv
            cd cmake_targets/ran_build/build
            ###########################################################
            echo -e "Selected scenario is ${SELECTED_SCENARIO}\n"
            shift 2;;
        -p | --plmn)
            SELECTED_PLMN=$2
            if [[ ! $SELECTED_PLMN =~ $re ]] || [[ $SELECTED_PLMN -gt ${#PLMNS[@]} ]] || [[ $SELECTED_PLMN -le 0 ]] ; then
               echo -e "${R}selected PLMN is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
            shift 2;;  
        -o | --scope)
            NRSCOPE="-d"
            shift;; 
	-h | --help)
            print_help
            exit 0;;
        *) 
            exit
            ;;    
    esac
  done
# check if script is run with sudo privilages
SCRIPTUSER=$(whoami)
if [[ $SCRIPTUSER = "root" ]] ; then 
echo -e "${R}you should not run script with sudo privilages\n${NOCOLOR}"
echo -e "${R}remove sudo and execute again  \n${NOCOLOR}"               
exit 1
fi
############# compose command with arguments for the specific scenario ####
${SCENARIOS["$SELECTED_SCENARIO"-1]}  
echo -e $COMMAND | xclip 
# start execution of nr-softmodem for the selected scenario and PLMN   
echo -e $(xclip -o) | sudo bash # execute command from clipboard  
# end of script
}
  main "$@"


