#!/bin/bash
# oai 5G testbed with USRP N310
# UOP
# DCS LAB Feb 2024
# Manolis Bozis
# scripts MUST run with root privillages

#---------COLOR CODES --------------------
R='\033[0;31m'   #'0;31' is Red's ANSI color code
G='\033[0;32m'   #'0;32' is Green's ANSI color code
NOCOLOR='\033[0m'
###############################
# the followin variable needs to be updated when new scenarios are added
USERFOLDER="/home/manolis"
SCENARIOS=( "sa_51prb" "sa_106prb" "sa_106prb_TDD_1" "sa_106prb_TDD_2" "sa_106prb_tracer" "sa_106prb_mimo" "sa_133prb_mimo" \
 "sa_band78_133prb" "sa_band78_162prb" )
re='^[0-9]+$'    # integer value for selected scenario to be checked



#### FUNCTION 1 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023
Tool to start gnb softmodem for a particular scenorio using USRP N310 SDR device
or 2 hosts running OAI nrUE and nrgNB respectively.
the ethernet link between the host and SDR needs to be at least 10Gbps 

Usage:  $0 [OPTION]... [+VALUE] 
  -s, --scenario [value]   start gnb softmodem executing scenario number [value]
                           YOU NEED TO RUN WITH SUDO PRIVILAGES FOR "-s" OPTION
                           value is from the following table
                           ------------------------------------------------------------------
                          | 1 | standalone mode band 78 with 51prb (SISO)                    |
                          | 2 | standalone mode band 78 with 106prb (SISO)                   |
                          | 3 | standalone mode band 78 with 106prb TDD 1 slot configuration |
                          |   | with 7 DL, 2 UL, 1 FL slots, Periodicity=10 Slots (SISO)     |
                          | 4 | standalone mode band 78 with 106prb TDD 2 slot configuration |
                          |   | with 2 DL, 1 UL, 1 FL slots, Periodicity=4 Slots  (SISO)     |
                          | 5 | standalone mode band 78 with 106prb and radio packets        |
                          |   | capture with T Tracer  (SISO)                                |
                          | 6 | standalone mode band 78 with 106prb (MIMO 2x2)               |
                          | 7 | standalone mode band 78 with 133prb (MIMO 2x2)               |
                          | 8 | standalone mode band 78 with 133prb (SISO)                   |
                          | 9 | standalone mode band 78 with 162prb (SISO)                   |
                          -------------------------------------------------------------------
  -i, --info               show Open Air Interface version
  -h, --help               print this help message
EOF
}
#################################################

######### Function 2 51 PRB SA           ###################################
############## SCENARIO 1 ##################################################-
sa_51prb(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.sa.band78.51prb.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
#--MACRLCs.[0].ul_max_mcs 16 
# --continuous-tx --MACRLCs.[0].ul_max_mcs 25 
# -d  # uncomment the line to use scope
#--tune-offset 20000000
# --continuous-tx 
#--T_stdout 2  
# > ~/gnb.log 2>&1
# Tracer util usage with:--T_stdout 2
#--opt.type wireshark --opt.ip 127.0.0.1 
# --opt.path /home/manolis/scripts/captures/
#  --continuous-tx --d
# " --MACRLCs.[0].ul_max_mcs 14 " reduces heavy UL traffic by setting max MCS in UPLINK, "-d" starts the scope utility
# There is noise on the DC carriers on N300 and especially the X300 in UL.
#  To avoid their use or shift them away from the center to use more UL spectrum,
#  use the --tune-offset <Hz> command line switch, where <Hz> is ideally half 
# the bandwidth, or possibly less.
# --gNBs.[0].min_rxtxtime 6
# uncomment the following line to mitigate uplink issues rellated to noise 
# on the DC carriers
#--tune-offset <Hz>
#
}

############################################################################

######### Function 3 106 PRB SA           ###################################
############## SCENARIO 2 ##################################################-
sa_106prb(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
#--MACRLCs.[0].ul_max_mcs 16 
}

############################################################################

######### Function 4 SA mode band 78 106prb TDD 1  ########################
############## SCENARIO 3 ##################################################-
sa_106prb_TDD_1(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310_TDD_1.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
#--MACRLCs.[0].ul_max_mcs 16 
}
############################################################################

######### Function 5 SA mode band 78 106prb TDD 2  ########################
############## SCENARIO 4 ##################################################-
sa_106prb_TDD_2(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310_TDD_2.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
#--MACRLCs.[0].ul_max_mcs 16 
}
############################################################################

############## SCENARIO 5 ##################################################-
sa_106prb_tracer(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
--T_stdout 2 \ 
#> ~/gnb.log 2>&1
# Tracer util usage with:--T_stdout 2
#--MACRLCs.[0].ul_max_mcs 16 
}

############################################################################

######### Scenario 6 SA mode band 78 106 prb (2x2 MIMO) ###################
sa_106prb_mimo(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/2x2/gnb.band78.sa.fr1.106PRB.2x2.usrpn310.conf  \
--sa  --usrp-tx-thread-config 1 --thread-pool 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14 --gNBs.[0].min_rxtxtime 6 -A 45 
}
############################################################################

######### Scenario 7 SA mode band 78 133 prb (2x2 MIMO)  ###################
sa_133prb_mimo(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/2x2/gNB_SA_n78_133PRB.2x2_usrpn310.conf \
--sa --usrp-tx-thread-config 1 --gNBs.[0].min_rxtxtime 6 -A 45  
}

######## Scenario 8 SA mode band 78 133 prb SISO #########################
sa_band78_133prb(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gNB_SA_n78_133PRB.usrpn310.conf \
--sa --usrp-tx-thread-config 1 --gNBs.[0].min_rxtxtime 6 -A 45 \
#-d
}
############################################################################

############################################################################
######### Scenario 9 SA mode band 78 162 prb  SISO ########################
sa_band78_162prb(){
./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.162PRB.usrpn310.conf \
--sa --usrp-tx-thread-config 1 --gNBs.[0].min_rxtxtime 6 -A 45 
}
############################################################################


######################## MAIN FUNCTION #####################################
function main() {

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###########################################################

# check arguments

  until [ -z "$1" ]
  do
    case "$1" in
       -i | --info)
            echo "getting the version of OAI software..."
            sleep 1
            cd ${USERFOLDER}/openairinterface5g/
            echo -e "The version of the Open Air Interface is: $(git show | grep 'Merge branch' | cut -d "'" -f 2)\n"
            shift;;
       -s | --scenario)
	    # check if scenario value is valid
            SELECTED_SCENARIO=$2
            if [[ ! $SELECTED_SCENARIO =~ $re ]] || [[ $SELECTED_SCENARIO -gt ${#SCENARIOS[@]} ]] || [[ $SELECTED_SCENARIO -le 0 ]] ; then
               echo -e "${R}selected senario is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################

	    # check if script is run with sudo privilages
            SCRIPTUSER=$(whoami)
            if [[ $SCRIPTUSER != "root" ]] ; then 
               echo -e "${R}script must be run with sudo privilages\n${NOCOLOR}"
            exit 1
            fi
	    # check if core network is up, executing a ping to AMF ####
            echo -e "checking connection to AMF...\n"
            ping amf -c 1 > /dev/null
            if [ $? -ne 0 ]; then
            echo -e "${R} No connection to AMF\n"
            echo -e "start 5G core network prior to executing RAN ${NOCOLOR}\n"
            exit 1
            fi 
            ###########################################################
            # check cpu state #########################################
            cpufreq-info | awk '/analyzing CPU/ || /current CPU frequency is/ {print}'
            ###########################################################
            # switch to softmodem binary file folder ##################
            cd ${USERFOLDER}/openairinterface5g
            source oaienv
            cd cmake_targets/ran_build/build
            ###########################################################
            ${SCENARIOS["$SELECTED_SCENARIO"-1]}
            shift 2;;
	-h | --help)
            print_help
            exit 0;;
        *) 
            exit
            ;;
    esac
  done
# end of script
  }

main "$@"



