#!/bin/bash
# oai 5G testbed with USRP N310
# UOP
# DCS LAB Nov 2023
# Manolis Bozis
# scripts MUST run with root privillages

#---------COLOR CODES --------------------
R='\033[0;31m'   #'0;31' is Red's ANSI color code
G='\033[0;32m'   #'0;32' is Green's ANSI color code
NOCOLOR='\033[0m'
###############################
# the followin variable needs to be updated when new scenarios are added
USERFOLDER="/home/manolis"
SCENARIOS=( "sa_51prb" "sa_106prb" )
re='^[0-9]+$'    # integer value for selected scenatio to be checked



#### FUNCTION 1 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023
Tool to start gnb softmodem for a particular scenorio using USRP N310 SDR device
or 2 hosts running OAI nrUE and nrgNB respectively.
the ethernet link between the host and SDR needs to be at least 10Gbps 

Usage:  $0 [OPTION]... [+VALUE] 
  -s, --scenario [value]   start gnb softmodem executing scenario number [value]
                           YOU NEED TO RUN WITH SUDO PRIVILAGES FOR "-s" OPTION
                           value is from the following table
                           -----------------------------------------------------------------
                          | 1 | standalone mode band 78 with 51prb                         |
                          | 2 | standalone mode band 78 with 106prb                        |
                          ------------------------------------------------------------------
  -i, --info               show Open Air Interface version
  -h, --help               print this help message
EOF
}
#################################################

######### Function 2 51 PRB SA           ###################################
############## SCENARIO 1 ##################################################-
sa_51prb(){
./nr-softmodem -O ~manolis/scripts/configuration/gnb.sa.band78.51prb.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--MACRLCs.[0].ul_max_mcs 16 --gNBs.[0].min_rxtxtime 6 
# --continuous-tx --MACRLCs.[0].ul_max_mcs 25 
# -d  # uncomment the line to use scope
#--tune-offset 20000000
# --continuous-tx 
#--T_stdout 2  
# > ~/gnb.log 2>&1
# Tracer util usage with:--T_stdout 2
#--opt.type wireshark --opt.ip 127.0.0.1 
# --opt.path /home/manolis/scripts/captures/
#  --continuous-tx --d
# " --MACRLCs.[0].ul_max_mcs 14 " reduces heavy UL traffic by setting max MCS in UPLINK, "-d" starts the scope utility
# There is noise on the DC carriers on N300 and especially the X300 in UL.
#  To avoid their use or shift them away from the center to use more UL spectrum,
#  use the --tune-offset <Hz> command line switch, where <Hz> is ideally half 
# the bandwidth, or possibly less.
# --gNBs.[0].min_rxtxtime 6
# uncomment the following line to mitigate uplink issues rellated to noise 
# on the DC carriers
#--tune-offset <Hz>
#
}

############################################################################

######### Function 3 106 PRB SA           ###################################
############## SCENARIO 2 ##################################################-
sa_106prb(){
./nr-softmodem -O ~manolis/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--MACRLCs.[0].ul_max_mcs 16 --gNBs.[0].min_rxtxtime 6 
}

############################################################################




######################## MAIN FUNCTION #####################################
function main() {

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###########################################################

# check arguments

  until [ -z "$1" ]
  do
    case "$1" in
       -i | --info)
            echo "getting the version of OAI software..."
            sleep 1
            cd ${USERFOLDER}/openairinterface5g/
            echo -e "The version of the Open Air Interface is: $(git show | grep 'Merge branch' | cut -d "'" -f 2)\n"
            shift;;
       -s | --scenario)
	    # check if scenario value is valid
            SELECTED_SCENARIO=$2
            if [[ ! $SELECTED_SCENARIO =~ $re ]] || [[ $SELECTED_SCENARIO -gt ${#SCENARIOS[@]} ]] || [[ $SELECTED_SCENARIO -le 0 ]] ; then
               echo -e "${R}selected senario is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################

	    # check if script is run with sudo privilages
            SCRIPTUSER=$(whoami)
            if [[ $SCRIPTUSER != "root" ]] ; then 
               echo -e "${R}script must be run with sudo privilages\n${NOCOLOR}"
            exit 1
            fi
	    # check if core network is up, executing a ping to AMF ####
            echo -e "checking connection to AMF...\n"
            ping amf -c 1
            if [ $? -ne 0 ]; then
            echo -e "${R} No connection to AMF\n"
            echo -e "start 5G core network prior to executing RAN ${NOCOLOR}\n"
            exit 1
            fi 
            ###########################################################
            # check cpu state #########################################
            cpufreq-info | awk '/analyzing CPU/ || /current CPU frequency is/ {print}'
            ###########################################################
            # switch to softmodem binary file folder ##################
            cd ${USERFOLDER}/openairinterface5g
            source oaienv
            cd cmake_targets/ran_build/build
            ###########################################################
            ${SCENARIOS["$SELECTED_SCENARIO"-1]}
            shift 2;;
	-h | --help)
            print_help
            exit 0;;
        *) 
            exit
            ;;
    esac
  done
# end of script
  }

main "$@"



