#!/bin/bash
# oai 5G testbed with USRP N310
# UOP
# DCS LAB Feb 2024
# Manolis Bozis
# scripts MUST run with root privillages
# 
source gnbconfig.ini
# configure core network ips only if you change core network version or DHCP host IPs chenge ###
# run ./gnbconfig -a before running this script
################################
######################################################################################
######### FUCTIONS ############
#### FUNCTION 1 Exit Script ###
exitScript(){
echo -e "exiting....\n"
sleep 2
exit 1
}
###############################

###########################################################################
#### FUNCTION 2 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023-24
Tool to start gnb softmodem for a particular scenorio using Open Air Interface with RFsimulator
or 2 hosts running OAI nrUE and nrgNB respectively.
the ethernet link between the 2 hosts  needs to be at least 10Gbps 

Usage:  $0 [OPTION]... [+VALUE] 
  -s, --scenario [value]   start gnb softmodem executing scenario number [value]
                           value is from the following table
EOF
print_scenarios # print scenario descriptions (function is in gnbconfig.ini file)
cat <<EOF
                                                 
  -p, --plmn               PLMN selection
                           1 (default) --> 00101
                           2           --> 50501
                           3           --> 20295  
  -o, --scope              use nr-scope tool  
  -l, --log                write nr-softmodem output to a log file with date and time stamp in scripts/logs folder
  -t, --tracer             capture with T Tracer tool                        
  -i, --info               show Open Air Interface version
  -h, --help               print this help message
EOF
}
################# write to gnbconfig.ini file the selected scenario ########
write_selected_scenario(){
sed -i "/export SELECTED_SCENARIO/c\export SELECTED_SCENARIO=${SELECTED_SCENARIO}" ${USER_SCRIPTS_FOLDER}/gnbconfig.ini
}
############################################################################
################## SCENARIO 1 ##############################################
#################### SA mode band 78 51prb  ################################
sa_band78_24prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 2 ##############################################
#################### SA mode band 78 51prb  ################################
sa_band78_51prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 3 ##############################################
#################### SA mode band 78 106prb  ###############################
# 106 PRB - usrp n310 ######################################################
# configuration file used also for OTA transmittion with USRP N310 SDR #####
sa_band78_106prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
# add --telnetsrv \ # for telnet server in gnb
# add --MACRLCs.[0].ul_max_mcs # to select maximum mcs in uplink (default value is 9)
}
############################################################################

################## SCENARIO 4 ##############################################
########### SA mode band 78 133 prb SISO ###################################
sa_band78_133prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 5 ##############################################
############# SA mode band 78 162 prb  SISO ################################
sa_band78_162prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 6 ##############################################
######### Scenarion 17 SA mode band 78 217 prb SISO ########################
sa_band78_217prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 7 ##############################################
#################### SA mode band 77 273prb  ###############################
sa_band77_273prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 --usrp-tx-thread-config 1 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 8 ##############################################
##################### SA mode band 78 106prb TDD 1  ########################
sa_band78_106prb_TDD_1(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################


################## SCENARIO 9 ##############################################
##################### SA mode band 78 106prb TDD 2  ########################
sa_band78_106prb_TDD_2(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 10 ##############################################
##################### SA mode band 78 106 prb (2x2 MIMO) ###################
sa_mimo_band78_106prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 11 #############################################
##################### SA mode band 78 133 prb MIMO #########################
sa_mimo_band78_133prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 12 #############################################
##################### SA mode band 78 162 prb  MIMO ########################
sa_mimo_band78_162prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 13 #############################################
###################### SA mode band 78 217 prb MIMO ########################
sa_mimo_band78_217prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 14 #############################################
######### Scenarion 18 SA mode band 77 273 prb MIMO ########################
sa_mimo_band77_273prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

################## SCENARIO 15 ##############################################
#################### SA mode band 66 #######################################
sa_band66_106prb(){
COMMAND="LD_LIBRARY_PATH=. ./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--parallel-config PARALLEL_SINGLE_THREAD --rfsim --sa \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
# --rfsimulator.options chanmod --rfsimulator.modelname AWGN \
# uncomment previous line to define a channel model
# --telnetsrv 
#uncomment previous  line for telnet server
}
############################################################################
################## SCENARIO 16 ##############################################
#################### SA mode band 66 #######################################
sa_band71_106prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--parallel-config PARALLEL_SINGLE_THREAD --rfsim --sa \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
# --rfsimulator.options chanmod --rfsimulator.modelname AWGN \
# uncomment previous line to define a channel model
# --telnetsrv 
#uncomment previous  line for telnet server
}
############################################################################
################## SCENARIO 17 ######### ####################################
#################### Physical do-ra mode ###################################
dora(){
COMMAND="LD_LIBRARY_PATH=. ./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} \
--parallel-config PARALLEL_SINGLE_THREAD --rfsim --do-ra --rfsimulator.serveraddr server --gNBs.[0].min_rxtxtime 6"
}
############################################################################

############## SCENARIO 18 ##################################################
#################### Physical layer test ###################################
phytest(){
# only 1 slot assigned for downlink
COMMAND="LD_LIBRARY_PATH=. ./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--parallel-config PARALLEL_SINGLE_THREAD --rfsim --phy-test --gNBs.[0].min_rxtxtime 6"
}
############################################################################

############## SCENARIO 19 ##################################################
#################### Physical layer test with parameters  ##################
phytestextended(){
#  new parameters added
# -m     MCS (Modulation Coding Scheme)
# -M     number of resource blocks asigned
# -D     Bitmap of slots in downlink
# Selections are MCS=27 PRBs=106  
# and Bitmap of slots = 126 decimal = 01111110 binary that coresponds to slots 1,2,3,4,5 and 6
# at the UE side we see the number of HACKs are 6 times greater than in 1st scenario
COMMAND="LD_LIBRARY_PATH=. ./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--parallel-config PARALLEL_SINGLE_THREAD --rfsim --phy-test -m 27 -M 106 -D 126 --gNBs.[0].min_rxtxtime 6"
}
############################################################################

############## SCENARIO 20 ##################################################
#################### band 66, 25PRB, SCS=15KHz FDD ############################
band66_25prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
###############################################################################
############## SCENARIO 21 ##################################################
#################### GEO_satellite emulation  ###############################
geo_sat_emulation(){
# GEO satellite emulation --rfsimulator.prop_delay 238.74
# up to 16us (--rfsimulator.prop_delay 0.016) the UE receives the RAR and 
# completes the RAR proccess successfuly.
# This scenario is for transparent GEO satellite
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} --gNBs.[0].min_rxtxtime 6 --rfsim --sa  \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--rfsimulator.prop_delay 238.74 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
###############################################################################

################## SCENARIO 22 ##############################################
#################### SA mode band 3 #######################################
sa_band3_52prb(){
COMMAND="./nr-softmodem -O ${CONFIGURATION_FOLDER}/${CONFIGURATIONS[$SELECTED_SCENARIO-1]} \
--rfsimulator.serveraddr server --rfsimulator.serverport 4043 \
--parallel-config PARALLEL_SINGLE_THREAD --rfsim --sa \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################



######################## MAIN FUNCTION #####################################
function main() {

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###########################################################

# check arguments

  until [ -z "$1" ]
  do
    case "$1" in
       -i | --info)
            echo "getting the version of OAI software..."
            sleep 1
            cd ${USERFOLDER}/openairinterface5g/
            echo -e "The version of the Open Air Interface is: $(git show | grep 'Merge branch' | cut -d "'" -f 2)\n"
            exit 0;
            shift;;
       -s | --scenario)
	    # check if scenario value is valid
            SELECTED_SCENARIO=$2
            if [[ ! $SELECTED_SCENARIO =~ $re ]] || [[ $SELECTED_SCENARIO -gt ${#SCENARIOS[@]} ]] || [[ $SELECTED_SCENARIO -le 0 ]] ; then
               echo -e "${R}selected senario is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
            write_selected_scenario
	     # check if script is run with sudo privilages
	    SCRIPTUSER=$(whoami) 
            if [[ $SCRIPTUSER = "root" ]] ; then 
               echo -e "${R}you should not run script with sudo privilages\n${NOCOLOR}"
               echo -e "${R}try again without sudo \n${NOCOLOR}"               
            exit 1
            fi
	    # check if core network is up, executing a ping to AMF ####
            echo -e "checking connection to AMF...\n"
            ping ${AMF_IP} -c 1 > /dev/null
            if [ $? -ne 0 ]; then
            echo -e "${R} No connection to AMF\n"
            echo -e "start 5G core network prior to executing RAN ${NOCOLOR}\n"
            exit 1
            fi 
            ###########################################################
            # check cpu state #########################################
            cpufreq-info | awk '/analyzing CPU/ || /current CPU frequency is/ {print}'
            ###########################################################
            shift 2;;
	-p | --plmn)
            SELECTED_PLMN=$2
            if [[ ! $SELECTED_PLMN =~ $re ]] || [[ $SELECTED_PLMN -gt ${#PLMNS[@]} ]] || [[ $SELECTED_PLMN -le 0 ]] ; then
               echo -e "${R}selected PLMN is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
            # change PLMN settings with gnbconfig script ##############
             ./gnbconfig -p ${SELECTED_PLMN}
            ###########################################################
            shift 2;;            
	-o | --scope)
            NRSCOPE="-d"
            shift;;  
	-t | --tracer)
	    # Tracer util usage with:--T_stdout 2
            # IMPORTANT !!!!!!
            # if tracer tool is not build 
            # goto home/openairinterface5g/common/utis/T/tracer and run make command to build all executables needed
            TRACER=1
            shift;;               
        -l | --log)
            LOG=1
            shift;;                    
	-h | --help)
            print_help
            exit 0;;
        *) 
            exit
            ;;
    esac
  done


############# compose command with arguments for the specific scenario ####
${SCENARIOS["$SELECTED_SCENARIO"-1]}
##### write to log file ################################################### 
if [[ ${LOG} -eq 1 ]] && [[ ${TRACER} -eq 0 ]]; then
COMMAND="${COMMAND} 2>&1 |tee ${LOGS_FOLDER}/gnb_log_${LOG_FILE_TIMESTAMP}.txt"
fi
##### use tracer tool ################################################### 
if [[ ${TRACER} -eq 1 ]]; then
COMMAND="${COMMAND} --T_stdout 2 ${USERFOLDER}/scripts/logs/gnb_log_${LOG_FILE_TIMESTAMP}.txt 2>&1"
fi
##### add cpu affinity commannd in front of command to be executed ########
COMMAND="${CPU_AFFINITY}${COMMAND}"
########## copy command to clipboard ######################################
echo -e "${COMMAND}" | xclip 
########## copy command to file COMMAND ###################################
echo ${COMMAND} > COMMAND
# switch to softmodem binary file folder ##################
echo ${USERFOLDER}
cd ${USERFOLDER}/openairinterface5g
source oaienv
cd ${GNB_EXEC_FOLDER}
# start execution of nr-softmodem for the selected scenario and PLMN   
echo -e "$(xclip -o)" | sudo bash  # execute command from clipboard    
###  change owner and group of newly created log file #############
if [[ ${LOG} -eq 1 ]]; then
cd ${LOGS_FOLDER}
sudo chown ${USER} gnb_log_${LOG_FILE_TIMESTAMP}.txt
sudo chgrp ${USER} gnb_log_${LOG_FILE_TIMESTAMP}.txt
fi
###################################################################
### set null value in SELECTED_SCENARIO VAR in gnbconfig.ini file #
echo "reseting selected scenario variable in gnbconfig.ini file.."
SELECTED_SCENARIO=""
write_selected_scenario
###################################################################
# end of script
}

main "$@"