#!/bin/bash
# oai 5G testbed with USRP N310
# 
# DCS LAB Nov 2023
# Manolis Bozis
# scripts MUST run with root privillages
source ueconfig.ini
###############################


######### FUCTIONS ############
#### FUNCTION 1 Exit Script ###
exitScript(){
echo -e "exiting....\n"
sleep 2
exit 1
}
###############################

###########################################################################
#### FUNCTION 2 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023
Tool to start UE softmodem for a particular scenario using Open Air Interface
-the 2 hosts run OAI nrUE and nrgNB respectively.
-the ethernet link between the hosts and USRP N310 devices must be at least 10Gbps 

Usage:  $0 [OPTION]... [+VALUE] 
  -s, --scenario [value]   start UE softmodem selecting scenario number [value]
                           value is from the following table
                           ------------------------------------------------------------------
                          | 1 | standalone mode band 78 with 51prb  (SISO)                   |                          
                          | 2 | standalone mode band 78 with 106prb (SISO)                   |
                          | 3 | standalone mode band 78 with 133prb (SISO)                   |                      
                          | 4 | standalone mode band 78 with 162prb (SISO)                   |      
                          | 5 | standalone mode band 78 with 217prb (SISO)                   |  
                          | 6 | standalone mode band 77 with 273prb (SISO)                   |   
                          | 7 | standalone mode band 78 with 106prb TDD 1 slot configuration |
                          |   | with 7 DL, 2 UL, 1 FL slots, Periodicity=10 Slots            |
                          | 8 | standalone mode band 78 with 106prb TDD 2 slot configuration |
                          |   | with 2 DL, 1 UL, 1 FL slots, Periodicity=4 Slots             |                     
                          | 9 | standalone mode band 78 with 106prb (2x2 MIMO)               |
                          | 10| standalone mode band 78 with 133prb (2x2 MIMO)               |
                          | 11| standalone mode band 78 with 162prb (2x2 MIMO)               |     
                          | 12| standalone mode band 78 with 217prb (2x2 MIMO)               |  
                          | 13| standalone mode band 77 with 273prb (2x2 MIMO)               |
                          | 14| standalone mode band 66 with 106prb (SISO,FDD)               |        
                          -------------------------------------------------------------------
  -p, --plmn               PLMN selection
                           1 (default) --> 00101
                           2           --> 50501
                           3           --> 20295 
  -i, --info               show Open Air Interface version
  -l, --log                write nr-uesoftmodem output to a log file with date and time stamp in scripts/logs folder
  -o, --scope              use nr-scope tool 
  -c, --command_line       exit script, copy selected scenario command to file COMMAND in current folder
                           and start a new terminal in OAI binaries folder. 
                           -To view command before executing it type $(echo -e "${G}cat COMMAND${NOCOLOR}") in the command line. 
                           -To start gNB softmodem copy and paste command to new terminal window in OAI binaries folder
                           To go back to scripts folder type $(echo -e "${G}exit${NOCOLOR}")
  -h, --help               print this help message
EOF
}

############## SCENARIO 1 ##################################################-
#################### 51 prb SA #############################################
sa_51prb(){
COMMAND="./nr-uesoftmodem \
-r 51 --numerology 1 --band 78 -C 3309960000 --ssb 222 --ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "mgmt_addr=192.168.20.2,addr=192.168.20.2,clock_source=external,time_source=external" -A 45 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"

# -A 45: Sometimes, the nrUE would keep repeating RA procedure because of Msg3 failure at the gNB. If it happens, add the -A option at the nrUE and/or gNB side, e.g., -A 45.
#This modifies the timing advance (in samples). Adjust +/-5 if the issue persists.
#################################################################################
}

############## SCENARIO 2 ##################################################-
####################106 prb SA #############################################
sa_106prb(){
#################  106 PRB ######################################################
COMMAND="./nr-uesoftmodem \
-r 106 --numerology 1 --band 78 -C 3619200000 --ssb 516 --ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45  \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"

#-d
# --ue-fo-compensation --log_config.global_log_options level,nocolor,time
# -O ~/scripts/configuration/ue.conf 
# the above are other parameters you may need
#  --continuous-tx --d
# " --MACRLCs.[0].ul_max_mcs 14 " reduces heavy UL traffic by setting max MCS in UPLINK, "-d" starts the scope utility
# There is noise on the DC carriers on N300 and especially the X300 in UL.
#  To avoid their use or shift them away from the center to use more UL spectrum,
#  use the --tune-offset <Hz> command line switch, where <Hz> is ideally half 
# the bandwidth, or possibly less.
# uncomment the following line to mitigate uplink issues rellated to noise 
# on the DC carriers
#--tune-offset <Hz>
# -A 45: Sometimes, the nrUE would keep repeating RA procedure because of Msg3 failure at the gNB. If it happens, add the -A option at the nrUE and/or gNB side, e.g., -A 45.
#This modifies the timing advance (in samples). Adjust +/-5 if the issue persists
}
################################################################################

################## SCENARIO 3 #############################################
sa_band78_133prb(){
COMMAND="./nr-uesoftmodem \
-r 133 --numerology 1 --band 78 -C 3325620000 --ssb 144 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
 --sa --usrp-args "addr=192.168.20.2,clock_source=external,time_source=external" -A 45 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"

}

############################################################################

################## SCENARIO 4 #############################################
sa_band78_162prb(){
COMMAND="./nr-uesoftmodem \
-r 162 --numerology 1 --band 78 -C 3329760000 --ssb 516 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=external,time_source=external" -A 45 \
 --uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
 -O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
# --dlsch-parallel 3
}

############################################################################


################## SCENARIO 5 #############################################
sa_band78_217prb(){
COMMAND="./nr-uesoftmodem \
-r 217 --numerology 1 --band 78 -C 3339300000 --ssb 1152 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
# 
############################################################################

################## SCENARIO 6 #############################################
sa_band77_273prb(){
COMMAND="./nr-uesoftmodem \
-r 273 --numerology 1 --band 77 -C 3949740000 --ssb 1492 --ue-nb-ant-rx 1 --ue-nb-ant-tx 1 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45 \
 --uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
 -O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}

############################################################################

#### IMPORTANT !!! #########################################################
#### SCENARIOS 7 and 8 are the same with scenario 2 ########################
############################################################################

############## SCENARIO 9 ##################################################-
sa_mimo_106prb(){
#################  106 PRB (2x2 MIMO) #########################################
COMMAND="./nr-uesoftmodem \
-r 106 --numerology 1 --band 78 -C 3319680000 --ssb 516 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation  \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

############## SCENARIO 10 ##################################################-
sa_mimo_133prb(){
#################  133 PRB (2x2 MIMO) #####################################
COMMAND="./nr-uesoftmodem \
-r 133 --numerology 1 --band 78 -C 3325620000 --ssb 144 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

################## SCENARIO 11 #############################################
sa_mimo_band78_162prb(){
COMMAND="./nr-uesoftmodem \
-r 162 --numerology 1 --band 78 -C 3329760000 --ssb 516 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=external,time_source=external" -A 45 \
 --uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
 -O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
# --dlsch-parallel 3
}

############################################################################


################## SCENARIO 12 #############################################
sa_mimo_band78_217prb(){
COMMAND="./nr-uesoftmodem \
-r 217 --numerology 1 --band 78 -C 3339300000 --ssb 1152 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45 \
--uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
# 
############################################################################

################## SCENARIO 13 #############################################
sa_mimo_band77_273prb(){
COMMAND="./nr-uesoftmodem \
-r 273 --numerology 1 --band 77 -C 3949740000 --ssb 1492 --ue-nb-ant-rx 2 --ue-nb-ant-tx 2 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45 \
 --uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports2.xml \
 -O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}

############################################################################

################## SCENARIO 14 ##############################################
#################### SA mode band 66 #######################################
sa_band66(){
# band 66 
# FDD
# --numerology 1   (that means 30Khz subcarrier spacing)
# -r (Number of Physical Rsource Blocks PRBs)
# CO (Carrier Offset 400MHz)
# Carrier Frequency 2169080000 Hz
# --ssb (SSB subcarrier offset, substitutesthe older -s which is not valid now

COMMAND="./nr-uesoftmodem \
-r 106 --numerology 1 --band 66 -C 2169080000 --CO -400000000 --ssb 396 \
--ue-txgain ${OPTIMAL_OTA_UE_TX_GAIN} --ue-rxgain ${OPTIMAL_OTA_UE_RX_GAIN} --ue-fo-compensation \
--sa --usrp-args "addr=192.168.20.2,clock_source=internal,time_source=internal" -A 45 \
 --uecap_file ${CONFIGURATION_FOLDER}/uecap/uecap_ports1.xml \
-O ${CONFIGURATION_FOLDER}/${PLMNS["$SELECTED_PLMN"-1]}ue.conf ${NRSCOPE}"
}
############################################################################

######################## MAIN FUNCTION #####################################
function main() {

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###########################################################

# check arguments

  until [ -z "$1" ]
  do
    case "$1" in
       -i | --info)
            echo "getting the version of OAI software..."
            sleep 1
            cd ${USERFOLDER}/openairinterface5g/
            echo -e "The version of the Open Air Interface is: ${G}$(git show | grep 'Merge branch' | cut -d "'" -f 2)${NOCOLOR}\n"
            exit 0
            shift;;
       -s | --scenario)
	    # check if scenario value is valid
            SELECTED_SCENARIO=$2
            if [[ ! $SELECTED_SCENARIO =~ $re ]] || [[ $SELECTED_SCENARIO -gt ${#SCENARIOS[@]} ]] || [[ $SELECTED_SCENARIO -le 0 ]] ; then
               echo -e "${R}selected senario is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
	    # check if core network is up, executing a ping to AMF ####
            #echo -e "checking connection to AMF..."
            #ping amf -c 1 > /dev/null
            #if [ $? -ne 0 ]; then
            #echo -e "${R}\nNo connection to AMF\n"
            #echo -e "start 5G core network prior to executing RAN ${NOCOLOR}\n"
            #exit 1
            #else 
            #echo -e "${G}OK...${NOCOLOR}"
            #fi 
            ###########################################################
            # check cpu state #########################################
            CPUCORES=$(lscpu | awk '/^CPU\(s\)\:/ {print $2}')
            for ((i=1; i < $CPUCORES+1 ; i++)); do
            CPU_INDEX=$(( $i -1 ))
            CURRENT_GOVERNOR=$(cat /sys/devices/system/cpu/cpu${CPU_INDEX}/cpufreq/scaling_governor)
            if [[ ${CURRENT_GOVERNOR} != "performance" ]] ; then 
            WARNING_FLAG=1
            fi
            done
            if [[ ${WARNING_FLAG} -eq 1 ]] ; then
            echo -e "${Y}WARNING:CPU governor not set to performance. COnsider running ${G}sudo ./cpustress${Y} to set maximum performance for all CPUs${NOCOLOR}"
            fi
            ###########################################################
            # switch to softmodem binary file folder ##################
            cd ${USERFOLDER}/openairinterface5g 
            source oaienv
            cd cmake_targets/ran_build/build
            OAI_FOLDER=$(pwd)
            ###########################################################
            shift 2;;
        -p | --plmn)
            SELECTED_PLMN=$2
            if [[ ! $SELECTED_PLMN =~ $re ]] || [[ $SELECTED_PLMN -gt ${#PLMNS[@]} ]] || [[ $SELECTED_PLMN -le 0 ]] ; then
               echo -e "${R}selected PLMN is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
            shift 2;;  
        -o | --scope)
            NRSCOPE="-d"
            shift;;  
        -l | --log)
            LOG=1
            shift;;      
	-h | --help)
            print_help
            exit 0;;
        -c | --command_line)
            CL=1
            shift;;  
        *) 
            exit
            ;;    
    esac
  done
############# compose command with arguments for the specific scenario ####
${SCENARIOS["$SELECTED_SCENARIO"-1]}   
###########################################################################
# check if script is run with sudo privilages
SCRIPTUSER=$(whoami)
if [[ $SCRIPTUSER = "root" ]] ; then 
echo -e "${R}you should not run script with sudo privilages\n${NOCOLOR}"
echo -e "${R}when using the -c parameter \n${NOCOLOR}"               
exit 1
fi
##### write to log file ################################################### 
if [[ ${LOG} -eq 1 ]]; then
COMMAND="${COMMAND} 2>&1 |tee ${LOGS_FOLDER}/ue_log_${LOG_FILE_TIMESTAMP}.txt"
fi
###########################################################################
##### add cpu affinity commannd in front of command to be executed ########
COMMAND="${CPU_AFFINITY}${COMMAND}"
echo -e $COMMAND | xclip 
echo -e $COMMAND > ${USER_SCRIPTS_FOLDER}/UE_COMMAND 

############# check if command is to be executed inside the script ########
#############   or copied to clipboard                          ###########
if [[ ${CL} -eq 1 ]]; then
            cd ${OAI_FOLDER} # move to binaries folder
            cat <<EOF
$(echo -e "${G}the command to start nr-softmodem was saved in file COMMAND in the current folder\n${NOCOLOR}")
-To view command before executing it type $(echo -e "${G}cat COMMAND${NOCOLOR}") in the command line. 
-To start UE softmodem copy and paste command to new terminal window in OAI binaries folder
EOF
            export COMMAND
            export OAI_FOLDER
            export MESSAGE="to execute nr-softmodem copy and paste the following command to command line or type \$(xclip -o):\n "           
            # execute bash in the same environment to keep the current directory
            gnome-terminal --working-directory=${OAI_FOLDER} -- bash -c 'echo -e "${MESSAGE} sudo $COMMAND" ; bash'        
else  
            # start execution of nr-softmodem for the selected scenario and PLMN   
            echo -e $(xclip -o) | sudo bash # execute command from clipboard     
fi  
##############################################################################  
###  change owner and group of newly created log file #############
if [[ ${LOG} -eq 1 ]]; then
cd ${LOGS_FOLDER}
sudo chown ${USER} ue_log_${LOG_FILE_TIMESTAMP}.txt
sudo chgrp ${USER} ue_log_${LOG_FILE_TIMESTAMP}.txt
fi
###################################################################

  }
 
  main "$@"









 


