#!/bin/bash
# oai 5G testbed with USRP N310
# UOP
# DCS LAB Feb 2024
# Manolis Bozis
# scripts MUST run with root privillages

#---------COLOR CODES --------------------
R='\033[0;31m'   #'0;31' is Red's ANSI color code
G='\033[0;32m'   #'0;32' is Green's ANSI color code
Y='\033[0;33m'   #'0;33' is Yellow's ANSI color code
NOCOLOR='\033[0m'
############################## VARIABLES SECTION #####################################
# the followin variable needs to be updated when new scenarios are added
USERFOLDER="/home/manolis"
SCENARIOS=( "sa_51prb" "sa_106prb" "sa_106prb_TDD_1" "sa_106prb_TDD_2" "sa_106prb_tracer" "sa_106prb_mimo" "sa_133prb_mimo" \
 "sa_band78_133prb" "sa_band78_162prb" )
re='^[0-9]+$'    # integer value for selected scenario to be checked
PLMNS=( "PLMN_1_" "PLMN_2_" "PLMN_3_" )
SELECTED_PLMN=1 # default PLMN is 00101
# PLMNs List ##############
# PLMN1  --> 00101
# PLMN2  --> 50501
# PLMN3  --> 20295
###########################
UL_MAX_MCS=9   # Maximum mcs value for UL (default value is 9)
NRSCOPE="" # do not use nr-scope tool by default
CL=0       # default value for flag CL is execute directly from the script
           # if changed to 1 nr-softmodem command is copied to clipboard 
           # and script exits 
LOG=0      # do not write to a log file (default). You van change it with the -l argument
######################################################################################

#### FUNCTION 1 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023
Tool to start gnb softmodem for a particular scenorio using USRP N310 SDR device
or 2 hosts running OAI nrUE and nrgNB respectively.
the ethernet link between the host and SDR needs to be at least 10Gbps 

Usage:  $0 [OPTION]... [+VALUE] 
  -s, --scenario [value]   start gNB softmodem selecting scenario number [value]
                           --------------------------------------------------------   
                           | FOR "-s" OPTION AND WITHOUT "-c" PARAMETER SPECIFIED  |
                           | YOU MUST RUN SCRIPT WITH SUDO                         |
                           | IN ALL OTHER CASES RUN SCRIPT WITHOUT SUDO            |
                           --------------------------------------------------------
                           
                           value is from the following table
                           ------------------------------------------------------------------
                          | 1 | standalone mode band 78 with 51prb (SISO)                    |
                          | 2 | standalone mode band 78 with 106prb (SISO)                   |
                          | 3 | standalone mode band 78 with 106prb TDD 1 slot configuration |
                          |   | with 7 DL, 2 UL, 1 FL slots, Periodicity=10 Slots (SISO)     |
                          | 4 | standalone mode band 78 with 106prb TDD 2 slot configuration |
                          |   | with 2 DL, 1 UL, 1 FL slots, Periodicity=4 Slots  (SISO)     |
                          | 5 | standalone mode band 78 with 106prb and radio packets        |
                          |   | capture with T Tracer  (SISO)                                |
                          | 6 | standalone mode band 78 with 106prb (MIMO 2x2)               |
                          | 7 | standalone mode band 78 with 133prb (MIMO 2x2)               |
                          | 8 | standalone mode band 78 with 133prb (SISO)                   |
                          | 9 | standalone mode band 78 with 162prb (SISO)                   |
                          -------------------------------------------------------------------
  -p, --plmn               PLMN selection
                           1 (default) --> 00101
                           2           --> 50501
                           3           --> 20295   
  -o, --scope              use nr-scope tool              
  -l, --log                write nr-softmodem output to a log file with date and time stamp in scripts/logs folder                 
  -i, --info               show Open Air Interface version
  -h, --help               print this help message
  -c, --command_line       exit script, copy selected scenario command to a text file named COMMAND in the same folder
                           -To view command before executing it type $(echo -e "${G}cat COMMAND${NOCOLOR}") in the command line. 
                           -To start gNB softmodem copy and paste command to new terminal window in OAI binaries folder
EOF
}
#################################################


############## SCENARIO 1 ##################################################
############## 51 PRB SA  ##################################################
sa_51prb(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.sa.band78.51prb.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"

# --continuous-tx --MACRLCs.[0].ul_max_mcs 25 
# -d  # uncomment the line to use scope
#--tune-offset 20000000
# --continuous-tx 
#--T_stdout 2  
# > ~/gnb.log 2>&1
# Tracer util usage with:--T_stdout 2
#--opt.type wireshark --opt.ip 127.0.0.1 
# --opt.path ${USERFOLDER}/scripts/captures/
#  --continuous-tx --d
# " --MACRLCs.[0].ul_max_mcs 14 " reduces heavy UL traffic by setting max MCS in UPLINK, "-d" starts the scope utility
# There is noise on the DC carriers on N300 and especially the X300 in UL.
#  To avoid their use or shift them away from the center to use more UL spectrum,
#  use the --tune-offset <Hz> command line switch, where <Hz> is ideally half 
# the bandwidth, or possibly less.
# --gNBs.[0].min_rxtxtime 6
# uncomment the following line to mitigate uplink issues rellated to noise 
# on the DC carriers
#--tune-offset <Hz>
#
}

############################################################################


############## SCENARIO 2 ##################################################
#########           106 PRB SA           ###################################
sa_106prb(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}

############################################################################


############## SCENARIO 3 ##################################################
##################### SA mode band 78 106prb TDD 1  ########################
sa_106prb_TDD_1(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310_TDD_1.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################


############## SCENARIO 4 ##################################################
##################### SA mode band 78 106prb TDD 2  ########################
sa_106prb_TDD_2(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310_TDD_2.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

############## SCENARIO 5 ##################################################-
sa_106prb_tracer(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.usrpn310.conf --sa --usrp-tx-thread-config 1 \
--gNBs.[0].min_rxtxtime 6 -A 45 \
--T_stdout 2 \ 
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
#> ~/gnb.log 2>&1
# Tracer util usage with:--T_stdout 2
#--MACRLCs.[0].ul_max_mcs 16 
}

############################################################################

######### Scenario 6 SA mode band 78 106 prb (2x2 MIMO) ###################
sa_106prb_mimo(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.106PRB.2x2.usrpn310.conf  \
--sa  --usrp-tx-thread-config 1 --thread-pool 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14 --gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

######### Scenario 7 SA mode band 78 133 prb (2x2 MIMO)  ###################
sa_133prb_mimo(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gNB_SA_n78_133PRB.2x2_usrpn310.conf \
--sa --usrp-tx-thread-config 1 --gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}

######## Scenario 8 SA mode band 78 133 prb SISO #########################
sa_band78_133prb(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.133PRB.usrpn310.conf \
--sa --usrp-tx-thread-config 1 --gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################

############################################################################
######### Scenario 9 SA mode band 78 162 prb  SISO ########################
sa_band78_162prb(){
COMMAND="./nr-softmodem -O ${USERFOLDER}/scripts/configuration/gnb.band78.sa.fr1.162PRB.usrpn310.conf \
--sa --usrp-tx-thread-config 1 --gNBs.[0].min_rxtxtime 6 -A 45 \
--MACRLCs.[0].ul_max_mcs ${UL_MAX_MCS} ${NRSCOPE}"
}
############################################################################


######################## MAIN FUNCTION #####################################
function main() {

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###########################################################

# check arguments

  until [ -z "$1" ]
  do
    case "$1" in
       -i | --info)
            echo "getting the version of OAI software..."
            sleep 1
            cd ${USERFOLDER}/openairinterface5g/
            echo -e "The version of the Open Air Interface is: $(git show | grep 'Merge branch' | cut -d "'" -f 2)\n"
            exit 0;
            shift;;
       -s | --scenario)
	    # check if scenario value is valid
            SELECTED_SCENARIO=$2
            if [[ ! $SELECTED_SCENARIO =~ $re ]] || [[ $SELECTED_SCENARIO -gt ${#SCENARIOS[@]} ]] || [[ $SELECTED_SCENARIO -le 0 ]] ; then
               echo -e "${R}selected senario is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
	    # check if core network is up, executing a ping to AMF ####
            echo -e "checking connection to AMF..."
            ping amf -c 1 > /dev/null
            if [ $? -ne 0 ]; then
            echo -e "${R}\nNo connection to AMF\n"
            echo -e "start 5G core network prior to executing RAN ${NOCOLOR}\n"
            exit 1
            else 
            echo -e "${G}OK...${NOCOLOR}"
            fi 
            ###########################################################
            # check cpu state #########################################
            CPUCORES=$(lscpu | awk '/^CPU\(s\)\:/ {print $2}')
            for ((i=1; i < $CPUCORES+1 ; i++)); do
            CPU_INDEX=$(( $i -1 ))
            CURRENT_GOVERNOR=$(cat /sys/devices/system/cpu/cpu${CPU_INDEX}/cpufreq/scaling_governor)
            if [[ ${CURRENT_GOVERNOR} != "performance" ]] ; then 
            WARNING_FLAG=1
            fi
            done
            if [[ ${WARNING_FLAG} -eq 1 ]] ; then
            echo -e "${Y}WARNING:CPU governor not set to performance. COnsider running ${G}sudo ./cpustress${Y} to set maximum performance for all CPUs${NOCOLOR}"
            fi
            shift 2;;
         -p | --plmn)
            SELECTED_PLMN=$2
            if [[ ! $SELECTED_PLMN =~ $re ]] || [[ $SELECTED_PLMN -gt ${#PLMNS[@]} ]] || [[ $SELECTED_PLMN -le 0 ]] ; then
               echo -e "${R}selected PLMN is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
            # change PLMN settings with gnbconfig script ##############
            ./gnbconfig -p ${SELECTED_PLMN}
            ###########################################################
            shift 2;;   
	-o | --scope)
            NRSCOPE="-d"
            shift;;                               
	-h | --help)
            print_help
            exit 0;;
        -c | --command_line)
            CL=1
            shift;;         
        -l | --log)
            LOG=1
            shift;;                    
        *) 
            exit
            ;;
    esac
  done
############# compose command with arguments for the specific scenario ####
${SCENARIOS["$SELECTED_SCENARIO"-1]}  
##### write to log file ################################################### 
if [[ ${LOG} -eq 1 ]]; then
COMMAND="${COMMAND} 2>&1 |tee ${USERFOLDER}/scripts/logs/gnb_log_$(date +%d_%m_20%y_at_%H_%M_%S).txt"
fi
########################################################################### 
echo -e "${COMMAND}" | xclip 
###########################################################################
###########################################################
# switch to softmodem binary file folder ##################
cd ${USERFOLDER}/openairinterface5g 
source oaienv
OAI_FOLDER=$(pwd)
###########################################################

############# check if command is to be executed inside the script ########
#############   or copied to clipboard                          ###########
if [[ ${CL} -eq 1 ]]; then
            SCRIPTUSER=$(whoami)
            if [[ $SCRIPTUSER = "root" ]] ; then 
               echo -e "${R}you should not run script with sudo privilages\n${NOCOLOR}"
               echo -e "${R}when using the -c parameter \n${NOCOLOR}"               
            exit 1
            fi
            cat <<EOF
$(echo -e "${G}the command to start nr-softmodem was saved in file COMMAND in the current folder\n${NOCOLOR}")
-To view command before executing it type $(echo -e "${G}cat COMMAND${NOCOLOR}") in the command line. 
-To start gNB softmodem copy and paste command to new terminal window in OAI binaries folder
EOF
            export COMMAND
            export OAI_FOLDER
            export MESSAGE="to execute nr-softmodem copy and paste the following command to command line or type \$(xclip -o):\n "
            echo -e "sudo ${COMMAND}" > ${USERFOLDER}/scripts/COMMAND            
            # execute bash in the same environment to keep the current directory
            gnome-terminal --working-directory=${OAI_FOLDER} -- bash -c 'echo -e "${MESSAGE} sudo $COMMAND" ; bash'         
else
# check if script is run with sudo privilages
            SCRIPTUSER=$(whoami)
            if [[ $SCRIPTUSER != "root" ]] ; then 
               echo -e "${R}script must be run with sudo privilages\n${NOCOLOR}"
            exit 1
            fi     
            # start execution of nr-softmodem for the selected scenario and PLMN   
            echo -e "$(xclip -o)" | bash  # execute command from clipboard     
fi    
  }

main "$@"



