###### UE configuration file      #####################
###### general parameters section #####################
export USERFOLDER="/home/manolis"
export USER_SCRIPTS_FOLDER="${USERFOLDER}/scripts/"
export CONFIGURATION_FOLDER="${USERFOLDER}/scripts/configuration"
export GNB_EXEC_FOLDER=${USERFOLDER}"/openairinterface5g/cmake_targets/ran_build/build/" # Folder where nr-softmodem executable is
export CI_SCRIPTS_FOLDER=${USERFOLDER}"/openairinterface5g/ci-scripts/" # Folder where ci-scripts are
export LOGS_FOLDER="${USER_SCRIPTS_FOLDER}/logs"
export ROUTER_IP="195.251.38.129" # change this value to your router IP address
export EXT_DN_IP="192.168.70.135" # Ip of oai-ext-dn container
export UPF_IP="192.168.70.134" # IP address of oai-upf container
export UE_HOST_IP="195.251.38.151"
export CN_IP=

##########COLOR CODES #################################
export R='\033[0;31m'   #'0;31' is Red's ANSI color code
export G='\033[0;32m'   #'0;32' is Green's ANSI color code
export NOCOLOR='\033[0m'
#######################################################


##### UE parameters ##################################################
export OPTIMAL_OTA_UE_RX_GAIN=70   # this value is found empirically by conducting several tests
export OPTIMAL_OTA_UE_TX_GAIN=5
export CPU_AFFINITY="taskset --cpu-list 0-7 " # select the cores you want to allocate to nr-softmodm execution
#export CPU_AFFINITY=""


