#!/bin/bash
# oai 5G testbed with USRP N310
# 
# DCS LAB Aug 2024
# Manolis Bozis
source ueconfig.ini
######### FUCTIONS ############
#### FUNCTION 1 Exit Script ###
exitScript(){
echo -e "exiting....\n"
sleep 2
exit 1
}
###############################

###########################################################################
#### FUNCTION 2 print help message  ############
print_help(){
cat <<EOF
UOP - DCS LAB author Manolis Bozis 2023
Tool to configure UE softmodem for a particular PLMN

-the 2 hosts run OAI nrUE and nrgNB respectively.
-the ethernet link between the hosts and USRP N310 devices must be at least 10Gbps 

Usage:  $0 [OPTION]... [+VALUE] 
  -p, --plmn               PLMN selection
                           1 (default) --> 00101
                           2           --> 50501
                           3           --> 20895 
  -e, --editor             choose editor
                           1 (default) --> nano
                           2           --> gedit                                                        
  -i, --info               show Open Air Interface software version
  -h, --help               print this help message
EOF
}



######################## MAIN FUNCTION #####################################
function main() {

if [ "$*" == "" ]; then
    >&2 echo -e "${R}No arguments provided. Printing help message.${NOCOLOR}"
    print_help
    exit 1
fi
###########################################################

# check arguments

  until [ -z "$1" ]
  do
    case "$1" in
       -i | --info)
            echo "getting the version of OAI software..."
            sleep 1
            cd ${OAI_FOLDER}
            echo -e "The version of the Open Air Interface is: $(git show | grep 'Merge branch' | cut -d "'" -f 2)\n"
            exit 0
            shift;;
        -p | --plmn)
            SELECTED_PLMN=$2
            if [[ ! $SELECTED_PLMN =~ $re ]] || [[ $SELECTED_PLMN -gt ${#PLMNS[@]} ]] || [[ $SELECTED_PLMN -le 0 ]] ; then
               echo -e "${R}selected PLMN is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
            shift 2;;  
        -e | --editor)
	    # check if scenario value is valid
            SELECTED_EDITOR=$2
            if [[ ! $SELECTED_EDITOR =~ $re ]] || [[ $SELECTED_EDITOR -gt ${#EDITORS[@]} ]] || [[ $SELECTED_EDITOR -le 0 ]] ; then
               echo -e "${R}selected editor is not valid\n${NOCOLOR}"
               print_help
               exit 1 
	    fi
            ###########################################################
           shift 2;;           
	-h | --help)
            print_help
            exit 0;;
        *) 
            exit
            ;;    
    esac
  done
# start nr=uesoftmodem program with selected parameters
cd ${CONFIGURATION_FOLDER}
${EDITORS["$SELECTED_EDITOR"-1]} ${PLMNS["$SELECTED_PLMN"-1]}ue.conf
# end of script
  }
 
  main "$@"









 


