###### UE configuration file      #####################
### DCS lab UOP, Author MAnolis Bozis 2023            #
#######################################################

###### folders configuration ###############################################################
export GNB_HOST_USER="manolis"                                                             #
export USERFOLDER="/home/manolis"                                                          #
export USER_SCRIPTS_FOLDER="${USERFOLDER}/scripts"                                         #
export CONFIGURATION_FOLDER="${USERFOLDER}/scripts/configuration"                          #
# Folder where nr-softmodem executable is                                                  #
export OAI_EXEC_FOLDER=${USERFOLDER}"/openairinterface5g/cmake_targets/ran_build/build"    #
export OAI_FOLDER=${USERFOLDER}"/openairinterface5g/"                                      #
# Folder where ci-scripts are                                                              #
export CI_SCRIPTS_FOLDER=${USERFOLDER}"/openairinterface5g/ci-scripts"                     #
export LOGS_FOLDER="${USER_SCRIPTS_FOLDER}/logs"                                           #
############################################################################################

##### Network Interface Controller settings (set them manually in this file) ################
export ROUTER_IP="7.7.7.129"  # change this value to your router IP address            #                   
export NICNAME_0="enp2s0"        # NIC used for RFSIMULATOR                                 #               
export NICNAME_1="enp1s0f0np0"     # NIC 1 to SDR                                           #                  
export NICNAME_2="enp1s0f1np1"     # NIC 2 to SDR                                           #
export NICNAME_4="enp0s31f6"     # NIC to LAN and internet                                  #
export UE_HOST_MAC="cc:96:e5:35:2a:ea"                                                      #
export GNB_HOST_MAC="84:69:93:80:08:d3"                                                     #                  
export LAN_B_ADDR="7.7.7.159"                                                          #            
export USRP_ADDR_IP_1="192.168.20.2"                                                        #
export USRP_ADDR_IP_2="192.168.10.2"                                                        #
export UE_USRP_SERIAL=3177E48        # <---replace with your device's serial number         #                      
export NETWORK_BUFFER=134217728                                                             #                  
export GNB_HOST_10GBPS_NIC_IP="192.168.0.1"                                                 #
#############################################################################################

###### network configuration (DO NOT CHANGE THE VALUES IN THIS PART) ########################
export UE_HOST_IP="7.7.7.145"; # controlled by ueconfig -a
export GNB_HOST_IP="7.7.7.158"; # controlled by ueconfig -a
export CN_IP="7.7.7.149"; # last written by gnbconfig -a
#############################################################################################


##########COLOR CODES & TABLE SELECTIONS ##########################
export R='\033[0;31m'   #'0;31' is Red's ANSI color code          #
export G='\033[0;32m'   #'0;32' is Green's ANSI color code        #
export NOCOLOR='\033[0m'                                          #
export EDITORS=( "nano" "gedit" )                                 #
export CLK_TIME_SELECTIONS=( "internal" "external" "gpsdo" )      #
###################################################################

###### UE RF configuration ###################################################################
export OPTIMAL_OTA_UE_RX_GAIN=45   # this value is found empirically by conducting several tests   
export OPTIMAL_OTA_UE_TX_GAIN=0                                                                   
#export UE_FO_COMENSATION="--ue-fo-compensation"                                                   
export UE_FO_COMENSATION="--ue-fo-compensation"                                                                        
#export OAI_RA_FIX="-A 45 "                                                                        
export OAI_RA_FIX=""                                                                               
export ONE_PPS_SOURCE=1                                                                            
export FREQUENCY_SOURCE=1                                                                          
###############################################################################################

function print_scenarios() {
cat << EOF 
                           ------------------------------------------------------------------
                          | 1 | standalone mode band 78 with 24prb  (SISO)                   |                            
                          | 2 | standalone mode band 78 with 51prb  (SISO)                   |                          
                          | 3 | standalone mode band 78 with 106prb (SISO)                   |
                          | 4 | standalone mode band 78 with 133prb (SISO)                   |                      
                          | 5 | standalone mode band 78 with 162prb (SISO)                   |      
                          | 6 | standalone mode band 78 with 217prb (SISO)                   |  
                          | 7 | standalone mode band 77 with 273prb (SISO)                   |   
                          | 8 | standalone mode band 78 with 106prb TDD 1 slot configuration |
                          |   | with 7 DL, 2 UL, 1 FL slots, Periodicity=10 Slots            |
                          | 9 | standalone mode band 78 with 106prb TDD 2 slot configuration |
                          |   | with 2 DL, 1 UL, 1 FL slots, Periodicity=4 Slots             |                     
                          | 10| standalone mode band 78 with 106prb (2x2 MIMO)               |
                          | 11| standalone mode band 78 with 133prb (2x2 MIMO)               |
                          | 12| standalone mode band 78 with 162prb (2x2 MIMO)               |     
                          | 13| standalone mode band 78 with 217prb (2x2 MIMO)               |  
                          | 14| standalone mode band 77 with 273prb (2x2 MIMO)               |
                          | 15| standalone mode band 66 with 106prb (SISO,FDD, 40MHz BWP)    |
                          | 16| standalone mode band 71 with 106prb (SISO,FDD, 20MHz BWP)    |                        
                          | 17| do-ra mode: simulated 5G NSA connection with only 5G         |
                          |   | terminals being present                                      |                                              
                          | 18| physical layer test with one slot assigned for downlink      |
                          | 19| extended phy layer test with parameters changed              |
                          |   | (parameters need to be changed directly to script code)      |  
                          | 20| standalone mode band 66 with 25 prb (SISO,FDD, 5MHz BWP)     | 
                          | 21| GEO trnasparent SAT emulation                                |
                          |   | (band 66 with 25 prb (SISO,FDD, 15KHz SCS)                   |  
                          | 22| standalone mode band 3 with 52prb (SISO,FDD, 10MHz BWP)      |                                                  
                          -------------------------------------------------------------------                                           
EOF
} 


#export CPU_AFFINITY="taskset --cpu-list 0-7 " # select the cores you want to allocate to nr-softmodm execution
export CPU_AFFINITY=""
# the followin variable needs to be updated when new scenarios are added
export SCENARIOS=( "sa_band78_24prb" "sa_band78_51prb" "sa_band78_106prb" "sa_band78_133prb" "sa_band78_162prb" "sa_band78_217prb" \
 "sa_band77_273prb" "sa_band78_106prb" "sa_band78_106prb" "sa_mimo_band78_106prb" \
 "sa_mimo_band78_133prb" "sa_mimo_band78_162prb" "sa_mimo_band78_217prb"  \
 "sa_mimo_band77_273prb" "sa_band66" "sa_band71" "dora" "phytest" "phytestextended" "band66_25prb" \
 "geo_sat_emulation" "band3_52prb" )
export PLMNS=( "PLMN_1_" "PLMN_2_" "PLMN_3_" )
export VERSIONS=( "v_1_5" "v_2_1_0" ) 
export SELECTED_PLMN=1 # default PLMN is 00101
# PLMNs List ##############
# PLMN1  --> 00101
# PLMN2  --> 50501
# PLMN3  --> 20295
###########################
export NRSCOPE="" # do not use nr-scope tool by default
export CL=0       # default value for flag CL is execute directly from the script
           # if changed to 1 nr-softmodem command is copied to clipboard 
           # and script exits 

